### ISSUE TITLE
[solved] URGENT ~ saved replies not working

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#1134]
Hi Support
Since the last update 1.7.0
The module saved replies is not working.

This happens on the answering or new email
![image](https://user-images.githubusercontent.com/902376/113276599-44d3e880-92e0-11eb-9b77-977a90deebfe.png)

editing saved replies is also an issue

New saved replies works when creating one.

Please could you urgently look into this
Matthew

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. Which PHP version? Any messages in Manage > Logs > App Logs?

**Comment by raramuridesign** [comment]
Here is system info
![image](https://user-images.githubusercontent.com/902376/113285720-92a21e00-92eb-11eb-8b41-9d8776d1df2f.png)

So I cleared the logs and then opened a new ticket - tried to choose a saved reply and get this in the logs
There is a lot of other info in the stack trace
does the info below help?

```
 Trying to access array offset on value of type bool {"userId":1,"email":"xx@xx.com","exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type bool at /home/projects/webapps/app-helpdesk/public/vendor/rap2hpoutre/laravel-log-viewer/src/controllers/LogViewerController.php:72)
[stacktrace]
#0 /home/projects/webapps/app-helpdesk/public/vendor/rap2hpoutre/laravel-log-viewer/src/controllers/LogViewerController.php(72): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 [internal function]: Rap2hpoutre\\LaravelLogViewer\\LogViewerController->index()
#2 /home/projects/webapps/app-helpdesk/public/overrides/Illuminate/Routing/Controller.php(54): call_user_func_array()
#3 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#4 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#5 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#6 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route->run()
#7 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#8 /home/projects/webapps/app-helpdesk/public/app/Http/Middleware/CheckRole.php(26): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#9 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\CheckRole->handle()
#10 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 /home/projects/webapps/app-helpdesk/public/app/Http/Middleware/CustomHandle.php(22): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#12 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\CustomHandle->handle()
#13 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /home/projects/webapps/app-helpdesk/public/app/Http/Middleware/LogoutIfDeleted.php(28): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#15 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\LogoutIfDeleted->handle()
#16 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /home/projects/webapps/app-helpdesk/public/app/Http/Middleware/Localize.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#18 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\Localize->handle()
#19 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /home/projects/webapps/app-helpdesk/public/app/Http/Middleware/HttpsRedirect.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#21 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\HttpsRedirect->handle()
#22 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#24 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#25 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#27 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#28 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#30 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#31 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#33 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#34 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/projects/webapps/app-helpdesk/public/app/Http/Middleware/TokenAuth.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#36 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\TokenAuth->handle()
#37 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#39 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle()
#40 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#42 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#43 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#45 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#46 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#48 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Pipeline\\Pipeline->then()
#49 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack()
#50 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute()
#51 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute()
#52 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch()
#53 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#54 /home/projects/webapps/app-helpdesk/public/app/Http/Middleware/TerminateHandler.php(12): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#55 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\TerminateHandler->handle()
#56 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /home/projects/webapps/app-helpdesk/public/app/Http/Middleware/ResponseHeaders.php(11): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#58 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\ResponseHeaders->handle()
#59 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /home/projects/webapps/app-helpdesk/public/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#61 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle()
#62 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#64 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#65 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#67 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#68 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#70 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#71 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#72 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#73 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#74 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#75 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#76 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then()
#77 /home/projects/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#78 /home/projects/webapps/app-helpdesk/public/public/index.php(64): Illuminate\\Foundation\\Http\\Kernel->handle()
#79 {main}
"}
                    
```

**Comment by raramuridesign** [comment]
Please note, we are having this same issue on 4 other helpdesks with exact same setup.

**Comment by freescout-helpdesk** [comment]
Try to clear browser cache. If the issue still persist feel free to send web and SSH/FTP access to your server to support@freescout.net

**Comment by sam-suresh** [comment]
I just upgraded today and facing same issue. 

Browser cache cleared. 
Application cache cleared. 
All modules up to date. 

No any error in App logs. 


App Version | 1.7.0    
-- | --
Apr 5, 2021 16:16
HTTPS
Apache/2.4.46 (Unix) OpenSSL/1.1.1
PHP 7.4.16
512M / 1024M

Saved Replies Active
Version: 1.0.6 |


<img width="753" alt="Screenshot 2021-04-05 at 4 18 06 PM" src="https://user-images.githubusercontent.com/5198092/113553621-a373cc00-962a-11eb-8d35-55b4bcb4a421.png">


<img width="121" alt="Screenshot 2021-04-05 at 4 18 37 PM" src="https://user-images.githubusercontent.com/5198092/113553629-a66ebc80-962a-11eb-885f-81c63bef8e1a.png">

**Comment by raramuridesign** [comment]
> Try to clear browser cache. If the issue still persist feel free to send web and SSH/FTP access to your server to [support@freescout.net](mailto:support@freescout.net)

Hi Support
I have sent email and access to our helpdesk.
You can reply via email on this.
thanks
M

**Comment by freescout-helpdesk** [comment]
It looks like something went wrong when you've updated Saved Replies Module to the latest version.

Try:
- manually delete all JS files from /public/js/builds
- reinstall Saved Replies module

**Comment by freescout-helpdesk** [comment]
@sam-suresh In /public/modules do you have symlinks or folders?

**Comment by raramuridesign** [comment]
Just a follow up here, and thanks to Freescout support for sorting this out.
The modules in the yourpath/public/modules/ folder require a sym link if these have somehow been manually created, this will cause the problem.

The fix is as follows, during this process NO DATA is removed.
- deactivate all modules
- delete all modules 
- install and activate modules one by one
- login via SSH and check the yourpath/public/modules folder to see if the new install has created sym links
- If yes, then check if saved replies is working

That's it
Thanks to support for solving this.
Matthew

**Comment by freescout-helpdesk** [comment]
Thanks for the follow up.

**Comment by sam-suresh** [comment]
> @sam-suresh In /public/modules do you have symlinks or folders?

I don't have any symlinks created there. 

I deleted the module and re-installed it. Still the same error.

**Comment by raramuridesign** [comment]
@sam-suresh recheck the guide above, there was a step missing.

**Comment by sam-suresh** [comment]
Thank you @raramuridesign. 

Deactivating and removing modules doesn't remove the `public/modules`. Removing it and reinstalling fixes this issue.
