### ISSUE TITLE
Hello I got a error, please help me.

### ISSUE THREAD

**Issue by swealpha** [freescout-helpdesk/freescout#1391]
Hello!

I get this issue, what can this be? :O Please help.

`The Process class relies on proc_open, which is not available on your PHP installation. {"exception":"[object] (Symfony\\Component\\Process\\Exception\\RuntimeException(code: 0): The Process class relies on proc_open, which is not available on your PHP installation. at /home/eplaf/domains/SECRET-DOMAIN-NAME.COM/public_html/vendor/symfony/process/Process.php:147)[stacktrace] #0 /home/eplaf/domains/SECRET-DOMAIN-NAME.COM/public_html/vendor/laravel/framework/src/Illuminate/Console/Scheduling/Event.php(200): Symfony\\Component\\Process\\Process->__construct(''/opt/alt/php73...', '/home/eplaf/dom...', NULL, NULL, NULL) #1 /home/eplaf/domains/SECRET-DOMAIN-NAME.COM/public_html/vendor/laravel/framework/src/Illuminate/Console/Scheduling/Event.php(176): Illuminate\\Console\\Scheduling\\Event->runCommandInForeground(Object(Illuminate\\Foundation\\Application)) #2 /home/eplaf/domains/SECRET-DOMAIN-NAME.COM/public_html/vendor/laravel/framework/src/Illuminate/Console/Scheduling/ScheduleRunCommand.php(59): Illuminate\\Console\\Scheduling\\Event->run(Object(Illuminate\\Foundation\\Application)) #3 [internal function]: Illuminate\\Console\\Scheduling\\ScheduleRunCommand->handle() #4 /home/eplaf/domains/SECRET-DOMAIN-NAME.COM/public_html/overrides/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array) #5 /home/eplaf/domains/SECRET-DOMAIN-NAME.COM/public_html/overrides/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}() #6 /home/eplaf/domains/SECRET-DOMAIN-NAME.COM/public_html/overrides/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure)) #7 /home/eplaf/domains/SECRET-DOMAIN-NAME.COM/public_html/overrides/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL) #8 /home/eplaf/domains/SECRET-DOMAIN-NAME.COM/public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array) #9 /home/eplaf/domains/SECRET-DOMAIN-NAME.COM/public_html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle)) #10 /home/eplaf/domains/SECRET-DOMAIN-NAME.COM/public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle)) #11 /home/eplaf/domains/SECRET-DOMAIN-NAME.COM/public_html/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput)) #12 /home/eplaf/domains/SECRET-DOMAIN-NAME.COM/public_html/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Console\\Scheduling\\ScheduleRunCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput)) #13 /home/eplaf/domains/SECRET-DOMAIN-NAME.COM/public_html/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput)) #14 /home/eplaf/domains/SECRET-DOMAIN-NAME.COM/public_html/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput)) #15 /home/eplaf/domains/SECRET-DOMAIN-NAME.COM/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput)) #16 /home/eplaf/domains/SECRET-DOMAIN-NAME.COM/public_html/artisan(43): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput)) #17 {main} "}`

**Comment by pmhtuk** [comment]
I assume you've hidden the domain (with secret-domain-name) but the first line gives a hint:

The Process class relies on proc_open, which is not available on your PHP installation.

**Comment by freescout-helpdesk** [comment]
Closing for no activity.
