### ISSUE TITLE
Email replies getting delivered a day later

### ISSUE THREAD

**Issue by taoeffect** [freescout-helpdesk/freescout#167]
So while testing this, I tried replying to a ticket, and the reply only got delivered like a day later. And it's random, sometimes the replies are delivered instantly.

**Comment by freescout-helpdesk** [comment]
Have you checked Logs and System Status?

**Comment by taoeffect** [comment]
Hmm, the system status is showing all OK, but one of the laravel logs did contain this:

```
[2018-12-01 10:23:00] production.ERROR: Class 'App\Console\Commands\Exception' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'App\\Console\\Commands\\Exception' not found at /var/www/freescout.git/app/Console/Commands/FetchEmails.php:150)
[stacktrace]
#0 /var/www/freescout.git/app/Console/Commands/FetchEmails.php(80): App\\Console\\Commands\\FetchEmails->fetch(Object(App\\Mailbox))
#1 [internal function]: App\\Console\\Commands\\FetchEmails->handle()
#2 /var/www/freescout.git/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#3 /var/www/freescout.git/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /var/www/freescout.git/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#5 /var/www/freescout.git/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#6 /var/www/freescout.git/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#7 /var/www/freescout.git/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#8 /var/www/freescout.git/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#9 /var/www/freescout.git/vendor/symfony/console/Application.php(946): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#10 /var/www/freescout.git/vendor/symfony/console/Application.php(248): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\FetchEmails), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#11 /var/www/freescout.git/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#12 /var/www/freescout.git/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 /var/www/freescout.git/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 /var/www/freescout.git/artisan(43): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 {main}
```

Not sure what to make of that?

**Comment by freescout-helpdesk** [comment]
Update app to the latest version.
