### ISSUE TITLE
Chat widget localStorage exception: access is denied for this document

### ISSUE THREAD

**Issue by rutger1140** [freescout-helpdesk/freescout#1683]
Hi,

We're trying to implement the chat widget on our website. The domain that is hosting FreeScout differs from the domain it is included in.

After disabling the `x-frame-options` header on our FreeScout instance the widget does show:
<img width="375" alt="img" src="https://user-images.githubusercontent.com/357924/151514554-ebd42eff-baa0-42e6-a4b0-e2842db98dab.png">

It doesn't work because of a JavaScript error:
```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at localStorageGet (https://freescoutdomain.com/js/builds/e7c0af26d498794dc6f8d6c39fca091c13136496974.js:448:31)
    at chatLoad (https://freescoutdomain.com/js/builds/e7c0af26d498794dc6f8d6c39fca091c13136496974.js:56:42)
    at HTMLDocument.<anonymous> (https://freescoutdomain.com/js/builds/e7c0af26d498794dc6f8d6c39fca091c13136496974.js:25:590)
    at l (https://freescoutdomain.com/js/builds/e7c0af26d498794dc6f8d6c39fca091c13136496974.js:1:29459)
    at c (https://freescoutdomain.com/js/builds/e7c0af26d498794dc6f8d6c39fca091c13136496974.js:1:29761)
```

Since the localStorage is only related to the specific domain, it can't be used across different domains.

Maybe this is related to additional security headers that are set? Why would a chat widget try to use the localStorage of it's parent window?

**Comment by freescout-helpdesk** [comment]
Can you post all the headers that are being sent to the browser by widget?

**Comment by rutger1140** [comment]
For: /modules/chat/js/widget.js
```
HTTP/2 200
server: nginx
date: Fri, 28 Jan 2022 10:47:44 GMT
content-type: text/javascript; charset=utf-8
content-length: 5698
last-modified: Thu, 13 Jan 2022 13:21:34 GMT
vary: Accept-Encoding
etag: "61e0275e-1642"
expires: Sun, 27 Feb 2022 10:47:44 GMT
cache-control: max-age=2592000
cache-control: public
accept-ranges: bytes
```

For: /chat/widget/form/xxxxx

```
HTTP/2 200 OK
server: nginx
content-type: text/html; charset=UTF-8
vary: Accept-Encoding
cache-control: max-age=0
date: Fri, 28 Jan 2022 10:45:55 GMT
pragma: no-cache
expires: Fri, 28 Jan 2022 10:45:55 GMT
x-ua-compatible: IE=edge
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
strict-transport-security: max-age=16070400; includeSubDomains
content-encoding: gzip
X-Firefox-Spdy: h2
```

Maybe related to the `x-content-type-options`?

I'd like to keep as much of those headers in there if possible.

**Comment by rutger1140** [comment]
I've tried to disable `referrer-policy`, `x-content-type-options`,`'x-frame-options` and `x-xss-protection` all together without success.

**Comment by freescout-helpdesk** [comment]
Check https://stackoverflow.com/questions/30481516/iframe-in-chrome-error-failed-to-read-localstorage-from-window-access-deni

**Comment by rutger1140** [comment]
I’ve seen that stackoverflow post. I wouldn’t want my customers to first change their browser settings before they’re able to chat with us. That’s bad for business. 

My personal browser cookie settings are somewhat more strict, I know that. But other websites with chat widgets work just fine with this setting enabled. 
Besides Firefox acting up, my iPhone isn’t working either. 

I hope this is something you can address in a future update. With the current setup we’re not able to use the chat widget.

**Comment by freescout-helpdesk** [comment]
If you wish feel free to send widget embed code to support@freescout.net, we'll take a look.

**Comment by freescout-helpdesk** [comment]
We could not reproduce the issue by settings same headers.

Does it work for you here https://freescout.net/chat-demo/ ?

**Comment by rutger1140** [comment]
It does work for me there. Maybe it has something to do with the headers from the page that is including it?

Will do some further digging on that.

**Comment by freescout-helpdesk** [comment]
> Maybe it has something to do with the headers from the page that is including it?

Feel free to post those headers too.

**Comment by freescout-helpdesk** [comment]
Closing for no activity.

**Comment by sm2x** [comment]
I am also experiencing exactly the same case, what is the cause of this, please
my version is 1.8.101

**Comment by freescout-helpdesk** [comment]
Can you reproduce the issue on https://freescout.net/chat-demo/ ?

**Comment by latamclickcom** [comment]
I am also experiencing exactly the same case. KB Widget. Version 1.8.128.
Refused to display 'https://www.latamclick.net/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
Please help.

**Comment by freescout-helpdesk** [comment]
https://freescout.net/module/chat/ --> Troubleshooting
