### ISSUE TITLE
Unable to start new conversations

### ISSUE THREAD

**Issue by TobiasValeur** [freescout-helpdesk/freescout#1789]
I have a mailbox set up correctly to receive and send mails through Outlook, but when i try to initiate a new conversation i either get the loader-main indefinitely

![image](https://user-images.githubusercontent.com/84373644/156593689-0dfbd5d1-232f-464e-a5d8-08ed4c129a15.png)

or it gets stuck loading on clicking send

![image](https://user-images.githubusercontent.com/84373644/156593589-4146fafb-5d5c-4a3a-8e86-c138b32c73aa.png)

I've tried looking through the logs but it doesn't seem like anything is printed.

**Comment by TobiasValeur** [comment]
Consistently getting this error:
```
Uncaught DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'http://_example.com_/conversation/140' cannot be created in a document with origin 'https://_example.com_' and URL 'https://_example.com_/mailbox/4/new-ticket'.
    at setUrl (https://_example.com_/js/builds/a32ab92fcf181a1e56bdc4b369733f3e73922715259.js:368:106)
    at Object.success (https://_example.com_/js/builds/a32ab92fcf181a1e56bdc4b369733f3e73922715259.js:365:442)
    at u (https://_example.com_/js/builds/a32ab92fcf181a1e56bdc4b369733f3e73922715259.js:1:27541)
    at Object.fireWith [as resolveWith] (https://_example.com_/js/builds/a32ab92fcf181a1e56bdc4b369733f3e73922715259.js:1:28286)
    at k (https://_example.com_/js/builds/a32ab92fcf181a1e56bdc4b369733f3e73922715259.js:1:77735)
    at XMLHttpRequest.<anonymous> (https://_example.com_/js/builds/a32ab92fcf181a1e56bdc4b369733f3e73922715259.js:1:79991)
```

**Comment by freescout-helpdesk** [comment]
Do you have non-official modules installed?
Can you reproduce it on demo.freescout.net?

**Comment by freescout-helpdesk** [comment]
Maybe your server sends some special headers...
