### ISSUE TITLE
[Fetch Error] Folder: INBOX; Error: Must use comma to separate addresses

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#1969]
Version 1.8.13

**Issue**
We have a fetch error, not sure when this happened or how.
We have 4 mailboxes and this is the only one giving troubles.

_Folder: INBOX; Error: Must use comma to separate addresses_

**Where**
When we test the mailbox connection, it results in this error.
![image](https://user-images.githubusercontent.com/902376/166643511-5ec8b1db-2e2f-453d-ac1a-8a06dc25fa15.png)

An urgent look into this would be appreciated as NO mails are being fetched right now.

M.

@freescout-helpdesk

**Comment by raramuridesign** [comment]
Not sure if this helps - but same time stamp the log shows this error @freescout-helpdesk 

`Call to a member function sortBy() on array {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function sortBy() on array at /home/home-helpdesk/webapps/app-helpdesk/public/app/Console/Commands/FetchEmails.php:1096)
[stacktrace]
#0 /home/home-helpdesk/webapps/app-helpdesk/public/app/Console/Commands/FetchEmails.php(221): App\\Console\\Commands\\FetchEmails->sortMessage()
#1 /home/home-helpdesk/webapps/app-helpdesk/public/app/Console/Commands/FetchEmails.php(94): App\\Console\\Commands\\FetchEmails->fetch()
#2 [internal function]: App\\Console\\Commands\\FetchEmails->handle()
#3 /home/home-helpdesk/webapps/app-helpdesk/public/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#4 /home/home-helpdesk/webapps/app-helpdesk/public/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#5 /home/home-helpdesk/webapps/app-helpdesk/public/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#6 /home/home-helpdesk/webapps/app-helpdesk/public/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#7 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#8 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#9 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run()
#10 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run()
#11 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand()
#12 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#13 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run()
#14 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run()
#15 /home/home-helpdesk/webapps/app-helpdesk/public/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle()
#16 {main}
"}`

**Comment by raramuridesign** [comment]
This has been sorted out, seems we had a rogue email.
M.
@freescout-helpdesk
