### ISSUE TITLE
[error log] Call to a member function sortBy() 

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#2000]
@freescout-helpdesk Here is a log entry which is throwing an error.
Any ideas?

```
Call to a member function sortBy() on array {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function sortBy() on array at /home/home-helpdesk/webapps/app-helpdesk/public/app/Console/Commands/FetchEmails.php:1096)
[stacktrace]
#0 /home/home-helpdesk/webapps/app-helpdesk/public/app/Console/Commands/FetchEmails.php(221): App\\Console\\Commands\\FetchEmails->sortMessage()
#1 /home/home-helpdesk/webapps/app-helpdesk/public/app/Console/Commands/FetchEmails.php(94): App\\Console\\Commands\\FetchEmails->fetch()
#2 [internal function]: App\\Console\\Commands\\FetchEmails->handle()
#3 /home/home-helpdesk/webapps/app-helpdesk/public/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#4 /home/home-helpdesk/webapps/app-helpdesk/public/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#5 /home/home-helpdesk/webapps/app-helpdesk/public/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#6 /home/home-helpdesk/webapps/app-helpdesk/public/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#7 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#8 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#9 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run()
#10 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run()
#11 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand()
#12 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#13 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run()
#14 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run()
#15 /home/home-helpdesk/webapps/app-helpdesk/public/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle()
#16 {main}
"}
```

**Comment by freescout-helpdesk** [comment]
Are you using non-official modules?
Are you using a modern Microsoft Exchange authentication?

**Comment by raramuridesign** [comment]
@freescout-helpdesk Nope. All modules are bought on the store.
We have: custom folders, saved replies, tags and workflows

**Comment by freescout-helpdesk** [comment]
There was a similar issue here: https://github.com/freescout-helpdesk/freescout/issues/1984#issuecomment-1122350438

**Comment by freescout-helpdesk** [comment]
Also what is your PHP version?

**Comment by raramuridesign** [comment]
@freescout-helpdesk 
PHP 7.4.28

**Comment by raramuridesign** [comment]
@freescout-helpdesk Frogot to answer your other question
We are using normal standard imap protocol nothing fancy

**Comment by freescout-helpdesk** [comment]
> Call to a member function sortBy() on array

This has been fixed in the `master` branch.
