### ISSUE TITLE
Bug: Customer reply duplication loop

### ISSUE THREAD

**Issue by fvdm** [freescout-helpdesk/freescout#2003]
Our customers are reporting they receive the mails from FreeScout multiple times. In our Exchange logs I see that FreeScout is submitting each mail to the customers in duplication over a hundred times. Each duplicate has exactly the same Message-ID.

Error in the send log:

```
Call to a member function appendMessage() on null; File: /var/www/vhosts/freescout.domain/httpdocs/app/Jobs/SendReplyToCustomer.php (294)
```

Each duplicate has an error line in the Laravel log:

```log
Call to a member function appendMessage() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function appendMessage() on null at /var/www/vhosts/freescout.domain/httpdocs/app/Jobs/SendReplyToCustomer.php:294)
[stacktrace]
#0 [internal function]: App\\Jobs\\SendReplyToCustomer->handle()
#1 /var/www/vhosts/freescout.domain/httpdocs/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#2 /var/www/vhosts/freescout.domain/httpdocs/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 /var/www/vhosts/freescout.domain/httpdocs/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#4 /var/www/vhosts/freescout.domain/httpdocs/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#5 /var/www/vhosts/freescout.domain/httpdocs/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#6 /var/www/vhosts/freescout.domain/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\SendReplyToCustomer))
#7 /var/www/vhosts/freescout.domain/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\SendReplyToCustomer))
#8 /var/www/vhosts/freescout.domain/httpdocs/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#9 /var/www/vhosts/freescout.domain/httpdocs/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\SendReplyToCustomer), false)
#10 /var/www/vhosts/freescout.domain/httpdocs/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Array)
#11 /var/www/vhosts/freescout.domain/httpdocs/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\\Queue\\Jobs\\Job->fire()
#12 /var/www/vhosts/freescout.domain/httpdocs/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\\Queue\\Worker->process('database', Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Object(Illuminate\\Queue\\WorkerOptions))
#13 /var/www/vhosts/freescout.domain/httpdocs/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), 'database', Object(Illuminate\\Queue\\WorkerOptions))
#14 /var/www/vhosts/freescout.domain/httpdocs/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon('database', 'emails,default,...', Object(Illuminate\\Queue\\WorkerOptions))
#15 /var/www/vhosts/freescout.domain/httpdocs/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker('database', 'emails,default,...')
#16 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#17 /var/www/vhosts/freescout.domain/httpdocs/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#18 /var/www/vhosts/freescout.domain/httpdocs/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#19 /var/www/vhosts/freescout.domain/httpdocs/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#20 /var/www/vhosts/freescout.domain/httpdocs/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#21 /var/www/vhosts/freescout.domain/httpdocs/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#22 /var/www/vhosts/freescout.domain/httpdocs/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#23 /var/www/vhosts/freescout.domain/httpdocs/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#24 /var/www/vhosts/freescout.domain/httpdocs/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 /var/www/vhosts/freescout.domain/httpdocs/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 /var/www/vhosts/freescout.domain/httpdocs/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 /var/www/vhosts/freescout.domain/httpdocs/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 /var/www/vhosts/freescout.domain/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#29 /var/www/vhosts/freescout.domain/httpdocs/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 {main}
"}
```

We use simple SMTP/TLS without authentication, by using an Exchange connector for the server IP. Other apps with the same setup don't have duplication.

FreeScout v1.8.15
CentOS 7
PHP 7.4

**Comment by fvdm** [comment]
It appears the bug is caused in Mailbox > Connection settings > Fetching Emails > _IMAP Folder To Save Outgoing Replies_

When its value contains a space the customer mail gets stuck in a loop. Resulting in 200 outgoing mails.

**Comment by freescout-helpdesk** [comment]
Thanks. We'll check what can be done.

**Comment by freescout-helpdesk** [comment]
It looks like PHP IMAP extension can not work with IMAP folders containing spaces. Now there will be no reply duplication loops if IMAP folder contains spaces.
