### ISSUE TITLE
error logs: undefined constant FT_UID - assumed 'FT_UID'

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#2133]
@freescout-helpdesk 
We just picked up this error which is not allowing us to access freescout.
Could you urgently respond to let us know what this is all about.
Server: cpanel/whm
PHP: 7.4.x

```
[2022-08-03 12:10:04] production.ERROR: Use of undefined constant FT_UID - assumed 'FT_UID' (this will throw an Error in a future version of PHP) {"exception":"[object] (ErrorException(code: 0): Use of undefined constant FT_UID - assumed 'FT_UID' (this will throw an Error in a future version of PHP) at /home/helptreefla/public_html/vendor/webklex/laravel-imap/src/config/imap.php:105)
[stacktrace]
#0 /home/helptreefla/public_html/vendor/webklex/laravel-imap/src/config/imap.php(105): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Use of undefine...', '/home/helptreef...', 105, Array)
#1 /home/helptreefla/public_html/vendor/webklex/laravel-imap/src/IMAP/Providers/LaravelServiceProvider.php(66): require('/home/helptreef...')
#2 /home/helptreefla/public_html/vendor/webklex/laravel-imap/src/IMAP/Providers/LaravelServiceProvider.php(51): Webklex\\IMAP\\Providers\\LaravelServiceProvider->setVendorConfig()
#3 /home/helptreefla/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(586): Webklex\\IMAP\\Providers\\LaravelServiceProvider->register()
#4 /home/helptreefla/public_html/overrides/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(89): Illuminate\\Foundation\\Application->register(Object(Webklex\\IMAP\\Providers\\LaravelServiceProvider))
#5 /home/helptreefla/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(561): Illuminate\\Foundation\\ProviderRepository->load(Array)
#6 /home/helptreefla/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#7 /home/helptreefla/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#8 /home/helptreefla/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(296): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#9 /home/helptreefla/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(119): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#10 /home/helptreefla/public_html/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#11 {main}
"} 
```

We also get an error when trying to manually update freescount using
/tools.php

![image](https://user-images.githubusercontent.com/902376/182605044-723dccbc-51a3-409a-bdbe-06c2c26e0e05.png)

Could you let us know what this is about
Thanks
M

**Comment by raramuridesign** [comment]
@freescout-helpdesk any idea on this?

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/556#issuecomment-608338958

**Comment by raramuridesign** [comment]
@freescout-helpdesk Thanks, this is now working. Appreciate the info.
