### ISSUE TITLE
Chat widget silently breaks in Incognito mode

### ISSUE THREAD

**Issue by CherryDT** [freescout-helpdesk/freescout#2347]
When incognito mode is used in the browser (with "block third-party cookies" enabled, which is the default!), the chat widget doesn't work. Clicking "send" does nothing.

In the developer tools console, the following error can be found:

```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at localStorageGet (https://helpdesk.****/js/builds/e7c0af26d498794dc6f8d6c39fca091c13330639339.js:474:31)
    at chatLoad (https://helpdesk.****/js/builds/e7c0af26d498794dc6f8d6c39fca091c13330639339.js:62:42)
    at HTMLDocument.<anonymous> (https://helpdesk.****/js/builds/e7c0af26d498794dc6f8d6c39fca091c13330639339.js:25:590)
    at l (https://helpdesk.****/js/builds/e7c0af26d498794dc6f8d6c39fca091c13330639339.js:1:29459)
    at c (https://helpdesk.****/js/builds/e7c0af26d498794dc6f8d6c39fca091c13330639339.js:1:29761)
```

If the widget doesn't work in incognito mode, it should probably say so and ask the user to enable third-party cookies, instead of silently failing. Many users are using incognito mode to log in with another account temporarily, so there is a high likelyhood of encountering this issue.

Tested with Chrome 105.0.5195.127 on Windows 10.

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. "Block third-party cookies in Incognito" is On.

![2022-10-29_09-11-12](https://user-images.githubusercontent.com/40499291/198816822-ea7767a6-3c3c-40b6-a125-2fc1229f78f7.png)

Do you have any non-official modules installed? Do you have any other browser extensions which may cause this?

**Comment by freescout-helpdesk** [comment]
Closing for no activity.
