### ISSUE TITLE
Site hard hang after failed(?) module update.

### ISSUE THREAD

**Issue by askleo** [freescout-helpdesk/freescout#2379]
Had freescout working and working well at support.askleo.com. (EC2, Ubuntu server)
Went to the modules page and attempted and "Update" on the first module needing one. Sat for minutes. No activity other than greying out the update button.
Hit "Update" on another. Same thing.

Now the site is completely unresponsive. NO action. I either get 504 gateway timeouts, or (after moving the contents of the Modules folder somewhere else) "Whoops, looks like something went wrong — check logs in /storage/logs". I've rebooted the server with no effect.

Error in  laravel-2022-11-12.log appended below.

How do I fix this? (And what other information can I provide? Freescout UI is now completely unavailable to me.

[2022-11-12 15:21:01] production.ERROR: SQLSTATE[HY000] [2002] Connection timed out (SQL: insert into `modules` (`alias`, `active`) values (apiwebhooks, 0)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 2002): SQLSTATE[HY000] [2002] Connection timed out (SQL: insert into `modules` (`alias`, `active`) values (apiwebhooks, 0)) at /data/support/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Connection timed out at /data/support/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection timed out at /data/support/public_html/overrides/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)
[stacktrace]
#0 /data/support/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback()
#1 /data/support/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\\Database\\Connection->run()
#2 /data/support/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\\Database\\Connection->statement()
#3 /data/support/public_html/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\\Database\\Connection->insert()
#4 /data/support/public_html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2159): Illuminate\\Database\\Query\\Processors\\Processor->processInsertGetId()
#5 /data/support/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1285): Illuminate\\Database\\Query\\Builder->insertGetId()
#6 /data/support/public_html/overrides/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(722): Illuminate\\Database\\Eloquent\\Builder->__call()
#7 /data/support/public_html/overrides/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(687): Illuminate\\Database\\Eloquent\\Model->insertAndSetId()
#8 /data/support/public_html/overrides/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(550): Illuminate\\Database\\Eloquent\\Model->performInsert()
#9 /data/support/public_html/app/Module.php(51): Illuminate\\Database\\Eloquent\\Model->save()
#10 /data/support/public_html/app/Module.php(155): App\\Module::setActive()
#11 /data/support/public_html/app/Providers/AppServiceProvider.php(78): App\\Module::deactiveModule()
#12 [internal function]: App\\Providers\\AppServiceProvider->App\\Providers\\{closure}()
#13 /data/support/public_html/overrides/tormjens/eventy/src/Filter.php(28): call_user_func_array()
#14 /data/support/public_html/overrides/laravel/framework/src/Illuminate/Support/Collection.php(339): TorMorten\\Eventy\\Filter->TorMorten\\Eventy\\{closure}()
#15 /data/support/public_html/overrides/tormjens/eventy/src/Filter.php(29): Illuminate\\Support\\Collection->each()
#16 /data/support/public_html/vendor/tormjens/eventy/src/Events.php(163): TorMorten\\Eventy\\Filter->fire()
#17 /data/support/public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): TorMorten\\Eventy\\Events->filter()
#18 /data/support/public_html/overrides/nwidart/laravel-modules/src/Module.php(331): Illuminate\\Support\\Facades\\Facade::__callStatic()
#19 /data/support/public_html/overrides/nwidart/laravel-modules/src/Module.php(288): Nwidart\\Modules\\Module->registerFiles()
#20 /data/support/public_html/overrides/nwidart/laravel-modules/src/Repository.php(366): Nwidart\\Modules\\Module->register()
#21 /data/support/public_html/vendor/nwidart/laravel-modules/src/Providers/BootstrapServiceProvider.php(22): Nwidart\\Modules\\Repository->register()
#22 /data/support/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(586): Nwidart\\Modules\\Providers\\BootstrapServiceProvider->register()
#23 /data/support/public_html/vendor/nwidart/laravel-modules/src/ModulesServiceProvider.php(38): Illuminate\\Foundation\\Application->register()
#24 /data/support/public_html/vendor/nwidart/laravel-modules/src/LaravelModulesServiceProvider.php(15): Nwidart\\Modules\\ModulesServiceProvider->registerModules()
#25 [internal function]: Nwidart\\Modules\\LaravelModulesServiceProvider->boot()
#26 /data/support/public_html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#27 /data/support/public_html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#28 /data/support/public_html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#29 /data/support/public_html/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#30 /data/support/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(792): Illuminate\\Container\\Container->call()
#31 /data/support/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\\Foundation\\Application->bootProvider()
#32 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
#33 /data/support/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): array_walk()
#34 /data/support/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#35 /data/support/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
#36 /data/support/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(296): Illuminate\\Foundation\\Application->bootstrapWith()
#37 /data/support/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(119): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#38 /data/support/public_html/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle()
#39 {main}
"}

**Comment by askleo** [comment]
OK, somehow a database configuration setting had been reverted to a prior value. No idea why. I think I'm working again.

**Comment by freescout-helpdesk** [comment]
`Connection timed out` - it looks like you had some issues with DB.
