### ISSUE TITLE
module asking for update and there is no updates available.

### ISSUE THREAD

**Issue by arungowda325** [freescout-helpdesk/freescout#2480]
<img width="434" alt="image" src="https://user-images.githubusercontent.com/38986419/208642896-d3e36006-fb27-47bc-9be5-1c125910bbba.png">

**Comment by arungowda325** [comment]
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/38986419/208643077-69e06f91-f3f9-41cd-81f2-bd69f830c858.png">

Slack module showing this error and not able to use

**Comment by freescout-helpdesk** [comment]
Check Manage > System page and update FreeScout to the latest version.

Regarding the second issue - follow instruction and check logs in /storage/logs.

**Comment by arungowda325** [comment]
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/38986419/208643371-8bc93d6b-f716-467b-9bf5-04df776ebcf4.png">

**Comment by arungowda325** [comment]
/www/html/storage/logs/laravel-2022-12-20.log

[2022-12-20 15:52:30] production.ERROR: foreach() argument must be of type array|object, bool given (View: /www/html/Modules/Slack/Resources/views/settings.blade.php) (View: /www/html/Modules/Slack/Resources/views/settings.blade.php) {"userId":1,"email":"arun@****.com","exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, bool given (View: /www/html/Modules/Slack/Resources/views/settings.blade.php) (View: /www/html/Modules/Slack/Resources/views/settings.blade.php) at /data/storage/framework/views/08b28186983a9a9719e21f43434a9ce64a30b3e9.php:66, ErrorException(code: 0): foreach() argument must be of type array|object, bool given (View: /www/html/Modules/Slack/Resources/views/settings.blade.php) at /data/storage/framework/views/08b28186983a9a9719e21f43434a9ce64a30b3e9.php:66, ErrorException(code: 0): foreach() argument must be of type array|object, bool given at /data/storage/framework/views/08b28186983a9a9719e21f43434a9ce64a3459.php:66)
[stacktrace]
#0 /www/html/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(45): Illuminate\\View\\Engines\\CompilerEngine->handleViewException(Object(ErrorException), 0)
#1 /www/html/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\\View\\Engines\\PhpEngine->evaluatePath('/data/storage/f...', Array)
#2 /www/html/overrides/laravel/framework/src/Illuminate/View/View.php(137): Illuminate\\View\\Engines\\CompilerEngine->get('/www/html/resou...', Array)

**Comment by arungowda325** [comment]
Please help

**Comment by freescout-helpdesk** [comment]
Try to clear cache in Manage > System > Tools. If it does not help, you'll need to debug this: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Http/Controllers/SystemController.php#L195

**Comment by freescout-helpdesk** [comment]
For the slack issue create a separate issue.

**Comment by arungowda325** [comment]
Any updates?

**Comment by freescout-helpdesk** [comment]
Find someone who can debug it for you on your server.

**Comment by arungowda325** [comment]
How to fix this ? What is the issue? 
Please let me know how to debug. Im also a php developer. We paid for this fake module and not working. We were planning to buy some more modules and you guys are misleading us.

![image](https://user-images.githubusercontent.com/38986419/208839838-5513e13f-a392-4827-afd2-b044ffad420b.png)

![image](https://user-images.githubusercontent.com/38986419/208839760-c6787615-b934-4e68-9a43-a16b2e29119c.png)

**Comment by freescout-helpdesk** [comment]
You need to find out why your FreeScout does not show you the latest available for update version in Manage > System.
