### ISSUE TITLE
Transient migration error when updating from 1.8.36 to 1.8.43

### ISSUE THREAD

**Issue by maltem-za** [freescout-helpdesk/freescout#2484]
Feel free to close immediately, I just wanted to report a problem I experienced and how it was solved.

While updating from 1.8.36 to 1.8.43 (running on PHP 8.1.13) via the web interface I got the message that the update had failed. However, after refreshing the system status page it showed the new version.

Logs revealed the following migration error:
```
Undefined constant App\User::TYPE_ROBOT {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Undefined constant App\\User::TYPE_ROBOT at /etc/freescout/www/html/database/migrations/2022_12_18_010101_set_user_type_field.php:19)
[stacktrace]
#0 /etc/freescout/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(359): SetUserTypeField->up()
#1 /etc/freescout/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(366): Illuminate\\Database\\Migrations\\Migrator->Illuminate\\Database\\Migrations\\{closure}()
#2 /etc/freescout/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(177): Illuminate\\Database\\Migrations\\Migrator->runMigration()
#3 /etc/freescout/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(146): Illuminate\\Database\\Migrations\\Migrator->runUp()
#4 /etc/freescout/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(95): Illuminate\\Database\\Migrations\\Migrator->runPending()
#5 /etc/freescout/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(69): Illuminate\\Database\\Migrations\\Migrator->run()
#6 [internal function]: Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
...
```

I cleared the cache and retried the migration via the tools page, which now succeeded:

```
Migrating: 2022_12_18_010101_set_user_type_field
Migrated:  2022_12_18_010101_set_user_type_field
```

**Comment by freescout-helpdesk** [comment]
It will be fixed. In your case after manual migration everything should be fine.
