### ISSUE TITLE
Attachment and Saved Reply Issue

### ISSUE THREAD

**Issue by SecureCPU** [freescout-helpdesk/freescout#2566]
I started getting this issue today.

Every time I try to attach a file to an email or every time I try to use saved replies and add a link to the file I'm trying to attach.

![Screenshot_20230117_104320](https://user-images.githubusercontent.com/99109793/212945127-a686b9ab-e027-4b61-b5d0-48de20b00f9a.png)

I tried uninstalling and reinstalling saved replies. It helped for one email. Then started having the same issue again.
I tried the same with extended attachments, but it didn't make a difference

I checked the logs but can't seem to find anything.

**Comment by SecureCPU** [comment]
I do see this error, idk if its related.
`SQLSTATE[HY000]: General error: 2006 MySQL server has gone away {"exception":"[object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 2006 MySQL server has gone away at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php:202)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(202): PDO->rollBack()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(186): Illuminate\\Database\\Connection->performRollBack()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php(203): Illuminate\\Database\\Connection->rollBack()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(244): Illuminate\\Queue\\DatabaseQueue->pop()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(105): Illuminate\\Queue\\Worker->getNextJob()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#7 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#8 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#9 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#11 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#13 /var/www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run()
#15 /var/www/html/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run()
#16 /var/www/html/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand()
#17 /var/www/html/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run()
#20 /var/www/html/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle()
#21 {main}
"}`

**Comment by freescout-helpdesk** [comment]
Can you reproduce the issue on https://demo.freescout.net/ ?

**Comment by SecureCPU** [comment]
no.
I ran `sudo chown -R www-data:www-data /var/www/html` but that doesn't help. and everything shows as good on the system status page

**Comment by SecureCPU** [comment]
So I found out that it has to do with a file size limit. 
files that are only a couple KB, work. but anything larger doesn't

any idea how to fix that?

**Comment by SecureCPU** [comment]
update.
So i can upload differnt type of files.
i can upload .txt .json but I can't upload .pdf .docx .png or anything else.
i tried changing a .docx extension manually to .txt but that didn't help.

so now I'm very confused.

**Comment by SecureCPU** [comment]
Also, I can't seem to be able to paste things into the email.

For example, if I just type it's fine.

But if I paste then I start getting a pop-up saying `Error occurred. Please check your internet connection and try again.` that keeps popping up every 5 seconds until I refresh the page

**Comment by SecureCPU** [comment]
I think I found the Issue,
Doing a little testing. Will update as soon as I confirm

**Comment by SecureCPU** [comment]
I believe I found the issue.

For anyone using cloudflare, Security > WAF > Managed Rules > Cloudflare OWASP Core Ruleset <<< keep this off. When turned on, it started giving my FreeScout a bunch of issues and disconnecting my connection until I refreshed the page.

One of my guys turned it on a last week, turned it off, and now it seems to have cleared up the issues.
