### ISSUE TITLE
1.8.46 to 1.8.52 update failure

### ISSUE THREAD

**Issue by maxkvbn** [freescout-helpdesk/freescout#2597]
Hello.

After a couple of upgrades on old versions < 1.8.20, I have found the best way to update FreeScout is using "[Method 5. Update manually](https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout#method-5-update-manually)".
With minor issues, it has worked all the way to 1.8.46.
Today I updated from 1.8.46 to 1.8.52 and I get this:
```
[2023-01-20 10:54:08] production.ERROR: Class "Illuminate\Support\Facades\Event" not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class \"Illuminate\\Support\\Facades\\Event\" not found at /var/www/example.com/staging/vendor/laravel/framework/src/Illuminate/Foundation/Support/Providers/EventServiceProvider.php:33)
[stacktrace]
#0 /var/www/example.com/staging/app/Providers/EventServiceProvider.php(101): Illuminate\\Foundation\\Support\\Providers\\EventServiceProvider->boot()
#1 [internal function]: App\\Providers\\EventServiceProvider->boot()
#2 /var/www/example.com/staging/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#3 /var/www/example.com/staging/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /var/www/example.com/staging/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#5 /var/www/example.com/staging/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#6 /var/www/example.com/staging/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(792): Illuminate\\Container\\Container->call(Array)
#7 /var/www/example.com/staging/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\\Foundation\\Application->bootProvider(Object(App\\Providers\\EventServiceProvider))
#8 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(App\\Providers\\EventServiceProvider), 34)
#9 /var/www/example.com/staging/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): array_walk(Array, Object(Closure))
#10 /var/www/example.com/staging/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#11 /var/www/example.com/staging/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#12 /var/www/example.com/staging/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#13 /var/www/example.com/staging/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#14 /var/www/example.com/staging/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#15 /var/www/example.com/staging/public/index.php(83): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#16 {main}
"} 
```

I've tried the following commands:
```
composer update --ignore-platform-reqs
composer dump-autoload
```

I am unable to utilize any artisan commands, such as cache:clear/config:clear, due to the above error.

Do you have any pointers where to look?

**Comment by freescout-helpdesk** [comment]
When following `Method 5. Update manually` you don't need to run composer.

**Comment by maxkvbn** [comment]
I only ran the composer commands after getting the above error, to see if it would fix the site, which it did not.

Do you have any suggestions on how to get the site back online and upgraded?

**Comment by freescout-helpdesk** [comment]
Have you cleared the cache?

**Comment by maxkvbn** [comment]
When executing any artisan commands, such as cache:clear/config:clear, I also get the above error unfortunately.

**Comment by freescout-helpdesk** [comment]
Use the 3-rd method: https://github.com/freescout-helpdesk/freescout/wiki/Clearing-the-Cache

**Comment by maxkvbn** [comment]
It seems a file got corrupted during the file transfer. Redoing Method 5 from scratch again got the system online.

Thanks!
