### ISSUE TITLE
Error on updating from 1.8.50 to 1.8.52

### ISSUE THREAD

**Issue by maltem-za** [freescout-helpdesk/freescout#2598]
While updating from 1.8.50 to 1.8.52 (running on PHP 8.1.14) via the web interface I got the message that the update had failed. However, after refreshing the system status page it showed the new version and everything appears to be running normally.

Logs revealed the following error:

```
Call to undefined method App\Misc\Helper::isInstalled() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method App\\Misc\\Helper::isInstalled() at /etc/freescout/www/html/app/Console/Commands/ClearCache.php:58)
[stacktrace]
#0 [internal function]: App\\Console\\Commands\\ClearCache->handle()
#1 /etc/freescout/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#2 /etc/freescout/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 /etc/freescout/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#4 /etc/freescout/www/html/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#5 /etc/freescout/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#6 /etc/freescout/www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#7 /etc/freescout/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run()
#8 /etc/freescout/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(198): Illuminate\\Console\\Command->run()
#9 /etc/freescout/www/html/app/Console/Commands/AfterAppUpdate.php(40): Illuminate\\Console\\Command->call()
#10 [internal function]: App\\Console\\Commands\\AfterAppUpdate->handle()
...
```

**Comment by freescout-helpdesk** [comment]
It means update was successful. Just clear cache and run DB migration to make sure.
