### ISSUE TITLE
LDAP Module:  Error on Automatic Import

### ISSUE THREAD

**Issue by Bergrad** [freescout-helpdesk/freescout#2665]
PHP 8.1
Version 1.8.56
LDAD Module Version: 1.0.23

Hi Freescout Team,

after activation the Automatic Import in the LDAP Module, the Laravel-log shows every 15 Minutes this error:

`
Optional parameter $configuration declared before required parameter $name is implicitly treated as a required parameter {"exception":"[object] (ErrorException(code: 0): Optional parameter $configuration declared before required parameter $name is implicitly treated as a required parameter at /home/data/html/freescout/Modules/Ldap/vendor/adldap2/adldap2/src/AdldapInterface.php:23)
[stacktrace]
#0 /home/data/html/freescout/vendor/composer/ClassLoader.php(578): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /home/data/html/freescout/vendor/composer/ClassLoader.php(578): include()
#2 /home/data/html/freescout/vendor/composer/ClassLoader.php(432): Composer\\Autoload\\ClassLoader::Composer\\Autoload\\{closure}()
#3 /home/data/html/freescout/Modules/Ldap/vendor/adldap2/adldap2/src/Adldap.php(12): Composer\\Autoload\\ClassLoader->loadClass()
#4 /home/data/html/freescout/vendor/composer/ClassLoader.php(578): include('...')
#5 /home/data/html/freescout/vendor/composer/ClassLoader.php(432): Composer\\Autoload\\ClassLoader::Composer\\Autoload\\{closure}()
#6 /home/data/html/freescout/Modules/Ldap/Overrides/Adldap/Laravel/AdldapServiceProvider.php(149): Composer\\Autoload\\ClassLoader->loadClass()
#7 /home/data/html/freescout/Modules/Ldap/Overrides/Adldap/Laravel/AdldapServiceProvider.php(74): Adldap\\Laravel\\AdldapServiceProvider->newAdldap()
#8 /home/data/html/freescout/overrides/laravel/framework/src/Illuminate/Container/Container.php(749): Adldap\\Laravel\\AdldapServiceProvider->Adldap\\Laravel\\{closure}()
#9 /home/data/html/freescout/overrides/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\\Container\\Container->build()
#10 /home/data/html/freescout/overrides/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\\Container\\Container->resolve()
#11 /home/data/html/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\\Container\\Container->make()
#12 /home/data/html/freescout/overrides/laravel/framework/src/Illuminate/Container/Container.php(1198): Illuminate\\Foundation\\Application->make()
#13 /home/data/html/freescout/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(159): Illuminate\\Container\\Container->offsetGet()
#14 /home/data/html/freescout/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(128): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance()
#15 /home/data/html/freescout/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(215): Illuminate\\Support\\Facades\\Facade::getFacadeRoot()
#16 /home/data/html/freescout/Modules/Ldap/Overrides/Adldap/Laravel/AdldapServiceProvider.php(134): Illuminate\\Support\\Facades\\Facade::__callStatic()
#17 /home/data/html/freescout/Modules/Ldap/Providers/LdapServiceProvider.php(407): Adldap\\Laravel\\AdldapServiceProvider->addProviders()
#18 /home/data/html/freescout/Modules/Ldap/Providers/LdapServiceProvider.php(395): Modules\\Ldap\\Providers\\LdapServiceProvider::recreateAdldapSp()
#19 /home/data/html/freescout/Modules/Ldap/Providers/LdapServiceProvider.php(423): Modules\\Ldap\\Providers\\LdapServiceProvider::configureLdap()
#20 /home/data/html/freescout/Modules/Ldap/Console/Import.php(252): Modules\\Ldap\\Providers\\LdapServiceProvider::changeDn()
#21 /home/data/html/freescout/Modules/Ldap/Console/Import.php(47): Modules\\Ldap\\Console\\Import->getUsers()
#22 [internal function]: Modules\\Ldap\\Console\\Import->handle()
#23 /home/data/html/freescout/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#24 /home/data/html/freescout/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#25 /home/data/html/freescout/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#26 /home/data/html/freescout/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#27 /home/data/html/freescout/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#28 /home/data/html/freescout/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#29 /home/data/html/freescout/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run()
#30 /home/data/html/freescout/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run()
#31 /home/data/html/freescout/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand()
#32 /home/data/html/freescout/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#33 /home/data/html/freescout/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run()
#34 /home/data/html/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run()
#35 /home/data/html/freescout/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle()
#36 {main}
"}
`

thank you 
Alfred

**Comment by freescout-helpdesk** [comment]
Fixed in LDAP Module v1.0.24

**Comment by Bergrad** [comment]
Hi 

with Version LDAD Module Version: 1.0.24 the error message changed to:

` Optional parameter $attributes declared before required parameter $builder is implicitly treated as a required parameter {"exception":"[object] (ErrorException(code: 0): Optional parameter $attributes declared before required parameter $builder is implicitly treated as a required parameter at /home/data/html/freescout/Modules/Ldap/vendor/adldap2/adldap2/src/Models/Model.php:66)
[stacktrace]
#0 /home/data/html/freescout/vendor/composer/ClassLoader.php(578): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /home/data/html/freescout/vendor/composer/ClassLoader.php(578): include()
#2 /home/data/html/freescout/vendor/composer/ClassLoader.php(432): Composer\\Autoload\\ClassLoader::Composer\\Autoload\\{closure}()
#3 /home/data/html/freescout/Modules/Ldap/vendor/adldap2/adldap2/src/Models/Entry.php(12): Composer\\Autoload\\ClassLoader->loadClass()
#4 /home/data/html/freescout/vendor/composer/ClassLoader.php(578): include('...')
#5 /home/data/html/freescout/vendor/composer/ClassLoader.php(432): Composer\\Autoload\\ClassLoader::Composer\\Autoload\\{closure}()
#6 /home/data/html/freescout/Modules/Ldap/vendor/adldap2/adldap2/src/Models/User.php(22): Composer\\Autoload\\ClassLoader->loadClass()
#7 /home/data/html/freescout/vendor/composer/ClassLoader.php(578): include('...')
#8 /home/data/html/freescout/vendor/composer/ClassLoader.php(432): Composer\\Autoload\\ClassLoader::Composer\\Autoload\\{closure}()
#9 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()
#10 /home/data/html/freescout/Modules/Ldap/vendor/adldap2/adldap2/src/Query/Processor.php(151): class_exists()
#11 /home/data/html/freescout/Modules/Ldap/vendor/adldap2/adldap2/src/Query/Processor.php(132): Adldap\\Query\\Processor->newModel()
#12 /home/data/html/freescout/Modules/Ldap/vendor/adldap2/adldap2/src/Query/Processor.php(66): Adldap\\Query\\Processor->newLdapEntry()
#13 /home/data/html/freescout/Modules/Ldap/vendor/adldap2/adldap2/src/Query/Processor.php(94): Adldap\\Query\\Processor->process()
#14 /home/data/html/freescout/Modules/Ldap/Overrides/Adldap/Query/Builder.php(450): Adldap\\Query\\Processor->processPaginated()
#15 /home/data/html/freescout/Modules/Ldap/Overrides/Adldap/Query/Builder.php(346): Adldap\\Query\\Builder->compatiblePaginationCallback()
#16 /home/data/html/freescout/Modules/Ldap/Console/Sync.php(248): Adldap\\Query\\Builder->paginate()
#17 /home/data/html/freescout/Modules/Ldap/Console/Sync.php(46): Modules\\Ldap\\Console\\Sync->getUsers()
#18 [internal function]: Modules\\Ldap\\Console\\Sync->handle()
#19 /home/data/html/freescout/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#20 /home/data/html/freescout/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#21 /home/data/html/freescout/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#22 /home/data/html/freescout/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#23 /home/data/html/freescout/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#24 /home/data/html/freescout/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#25 /home/data/html/freescout/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run()
#26 /home/data/html/freescout/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run()
#27 /home/data/html/freescout/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand()
#28 /home/data/html/freescout/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#29 /home/data/html/freescout/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run()
#30 /home/data/html/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run()
#31 /home/data/html/freescout/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle()
#32 {main}
"}`

Automatic Import is not working. Cache is cleared.

best regards
Alfred

**Comment by freescout-helpdesk** [comment]
Check LDAP Module v1.0.25

**Comment by Bergrad** [comment]
No error Messages anymore, sync is running

Thanks a.
