### ISSUE TITLE
Can't create more than max_prepared_stmt_count statements

### ISSUE THREAD

**Issue by EgorKlochkov** [freescout-helpdesk/freescout#2781]
Hello!

The service did not work that night at 

laravel-2023-02-28.log:

```
[2023-02-28 09:30:04] production.ERROR: SQLSTATE[42000]: Syntax error or access violation: 1461 Can't create more than max_prepared_stmt_count statements (current value: 16382) {"exception":"[object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1461 Can't create more than max_prepared_stmt_count statements (current value: 16382) at /var/www/u1953887/data/www/ehelpdesk.ru/freescout/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1461 Can't create more than max_prepared_stmt_count statements (current value: 16382) at /var/www/u1953887/data/www/ehelpdesk.ru/freescout/overrides/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:82)
[stacktrace]
#0 /var/www/u1953887/data/www/ehelpdesk.ru/freescout/overrides/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(87): Doctrine\\DBAL\\Driver\\PDO\\Exception::new(Object(PDOException))
#1 /var/www/u1953887/data/www/ehelpdesk.ru/freescout/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(56): Doctrine\\DBAL\\Driver\\PDOConnection->prepare('set names 'utf8...')
#2 /var/www/u1953887/data/www/ehelpdesk.ru/freescout/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(30): Illuminate\\Database\\Connectors\\MySqlConnector->configureEncoding(Object(Doctrine\\DBAL\\Driver\\PDOConnection), Array)
#3 /var/www/u1953887/data/www/ehelpdesk.ru/freescout/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(183): Illuminate\\Database\\Connectors\\MySqlConnector->connect(Array)
#4 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#5 /var/www/u1953887/data/www/ehelpdesk.ru/freescout/vendor/laravel/framework/src/Illuminate/Database/Connection.php(915): call_user_func(Object(Closure))
#6 /var/www/u1953887/data/www/ehelpdesk.ru/freescout/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(108): Illuminate\\Database\\Connection->getPdo()
#7 /var/www/u1953887/data/www/ehelpdesk.ru/freescout/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(92): Illuminate\\Database\\Connection->createTransaction()
#8 /var/www/u1953887/data/www/ehelpdesk.ru/freescout/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php(195): Illuminate\\Database\\Connection->beginTransaction()
#9 /var/www/u1953887/data/www/ehelpdesk.ru/freescout/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(244): Illuminate\\Queue\\DatabaseQueue->pop('emails')
#10 /var/www/u1953887/data/www/ehelpdesk.ru/freescout/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(105): Illuminate\\Queue\\Worker->getNextJob(Object(Illuminate\\Queue\\DatabaseQueue), 'emails')
#11 /var/www/u1953887/data/www/ehelpdesk.ru/freescout/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon('database', 'emails,default,...', Object(Illuminate\\Queue\\WorkerOptions))
#12 /var/www/u1953887/data/www/ehelpdesk.ru/freescout/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker('database', 'emails,default,...')
#13 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#14 /var/www/u1953887/data/www/ehelpdesk.ru/freescout/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#15 /var/www/u1953887/data/www/ehelpdesk.ru/freescout/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 /var/www/u1953887/data/www/ehelpdesk.ru/freescout/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#17 /var/www/u1953887/data/www/ehelpdesk.ru/freescout/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#18 /var/www/u1953887/data/www/ehelpdesk.ru/freescout/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#19 /var/www/u1953887/data/www/ehelpdesk.ru/freescout/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#20 /var/www/u1953887/data/www/ehelpdesk.ru/freescout/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#21 /var/www/u1953887/data/www/ehelpdesk.ru/freescout/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 /var/www/u1953887/data/www/ehelpdesk.ru/freescout/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 /var/www/u1953887/data/www/ehelpdesk.ru/freescout/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 /var/www/u1953887/data/www/ehelpdesk.ru/freescout/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 /var/www/u1953887/data/www/ehelpdesk.ru/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 /var/www/u1953887/data/www/ehelpdesk.ru/freescout/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 {main}
"} 
```

Why could such an error occur?

**Comment by freescout-helpdesk** [comment]
"Short answer: increase max_prepared_stmt_count in MySQL server."
https://github.com/sysown/proxysql/issues/1251#issuecomment-345466058
