### ISSUE TITLE
Outgoing mail queue stopped running without any feedback

### ISSUE THREAD

**Issue by CodeAndWeb** [freescout-helpdesk/freescout#2808]
This is with Version 1.8.58
I just noticed that the outgoing mail queue was not processed for 4 weeks(!)...

News mails came in so I assumed that everything was ok. At least it seemed that the scheduler was running and processing new stuff.
We usually don't get much replies from users because we try to create good answers that immediately fix their issues. A very low number of users only asked questions twice and so I assumed that the first response went to their spam folder - but also no sign of big trouble.

It would really be great to get a warning if the mail queue is not working and mails are stuck. Preferably with a big fat banner at the top of the screen.

**Comment by freescout-helpdesk** [comment]
FreeScout sends alerts to admins when fetching does not happen for a while.
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#10-final-configuration

**Comment by freescout-helpdesk** [comment]
Is there anything in Manage > Logs > App Logs?

**Comment by CodeAndWeb** [comment]
Fetch mail log is ok.
queue-jobs.log had the last entry from 2023-02-02.

**Comment by CodeAndWeb** [comment]
I've meanwhile upgraded to the current release.

The lavavel.log contains an error

[2023-03-08 14:35:43] production.ERROR: There are no commands defined in the "scheduler" namespace.

Did you mean this?
    schedule {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): There are no commands defined in the \"scheduler\" namespace.

Did you mean this?
    schedule at /var/www/vendor/symfony/console/Application.php:579)
[stacktrace]
#0 /var/www/vendor/symfony/console/Application.php(632): Symfony\\Component\\Console\\Application->findNamespace()
#1 /var/www/vendor/symfony/console/Application.php(236): Symfony\\Component\\Console\\Application->find()
#2 /var/www/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#3 /var/www/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run()
#4 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run()
#5 /var/www/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle()
#6 {main}
"}

**Comment by freescout-helpdesk** [comment]
Now such alert will be shown if there are problems with background mail queue processing.

![2023-03-09_10-58-23](https://user-images.githubusercontent.com/40499291/223957682-6910be23-880b-42ce-87a9-9a51682542f6.png)

**Comment by CodeAndWeb** [comment]
This is perfect. Thanks a lot!
