### ISSUE TITLE
Undefined array key 0 /overrides/laravel/framework/src/Illuminate/Support/Collection.php:1710

### ISSUE THREAD

**Issue by githubuser-112** [freescout-helpdesk/freescout#3059]
Hi,

every few hours we get the following error:

```
Undefined array key 0 {"exception":"[object] (ErrorException(code: 0): Undefined array key 0 at /var/www/clients/client1/web11/web/overrides/laravel/framework/src/Illuminate/Support/Collection.php:1710)
[stacktrace]
#0 /var/www/clients/client1/web11/web/overrides/laravel/framework/src/Illuminate/Support/Collection.php(1710): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/clients/client1/web11/web/app/Subscription.php(161): Illuminate\\Support\\Collection->offsetGet()
#2 /var/www/clients/client1/web11/web/app/Subscription.php(327): App\\Subscription::usersToNotify()
#3 /var/www/clients/client1/web11/web/app/Console/Commands/FetchEmails.php(139): App\\Subscription::processEvents()
#4 [internal function]: App\\Console\\Commands\\FetchEmails->handle()
#5 /var/www/clients/client1/web11/web/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(28): call_user_func_array()
#6 /var/www/clients/client1/web11/web/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#7 /var/www/clients/client1/web11/web/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(27): Illuminate\\Container\\BoundMethod::callBoundMethod()
#8 /var/www/clients/client1/web11/web/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#9 /var/www/clients/client1/web11/web/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#10 /var/www/clients/client1/web11/web/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#11 /var/www/clients/client1/web11/web/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Symfony\\Component\\Console\\Command\\Command->run()
#12 /var/www/clients/client1/web11/web/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run()
#13 /var/www/clients/client1/web11/web/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand()
#14 /var/www/clients/client1/web11/web/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#15 /var/www/clients/client1/web11/web/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run()
#16 /var/www/clients/client1/web11/web/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run()
#17 /var/www/clients/client1/web11/web/artisan(60): Illuminate\\Foundation\\Console\\Kernel->handle()
#18 {main}
"}
```

Any idea what´s causing that and how to get rid of it?

Thanks a lot!

PHP version: 8.2.6
FreeScout version: 1.8.77

**Comment by freescout-helpdesk** [comment]
Should be fixed in the `master` branch.
