### ISSUE TITLE
Not all messages are downloaded...

### ISSUE THREAD

**Issue by Maddmax76** [freescout-helpdesk/freescout#3203]
Good morning. We have noticed that our FreeScout does not download all emails.
This happens in particular with reports coming from the old ticket management system.
when a user sends a request on the old system, this connects to the office365 smtp server, authenticates himself with the credentials of the user who generated the request and sends the email to the address of the mailbox associated with FreeScout.

If I open OutlookWebAccess on the mailbox associated with FreeScout, I see the message arrived in the name of the user who sent the request on the old system, waiting to be read. When the schedule that retrieves the messages runs, I see in OWA that the message is marked as READ, on the FreeScout site I don't see the request. There are no errors in the logs.

How can I investigate to figure out what's going on?

Thank you

PHP version: PHP 8.1.12-1
FreeScout version: 1.8.86

**Comment by janselato** [comment]
I have a similar problem. For now, I rolling back to 1.8.85.

https://github.com/freescout-helpdesk/freescout/issues/3202

**Comment by Maddmax76** [comment]
Thanks for the reply. 
Excuse my ignorance, how did you roll back? Is it just taking the files from the previous version and putting them in place of the new one or is there some function in the site?

**Comment by janselato** [comment]
I used this but downloaded the previous version:
https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout#method-5-update-manually

**Comment by Maddmax76** [comment]
perfect thank you very much. I will try to do a rollback in a moment of less intensive use of the FreeScout portal.

**Comment by freescout-helpdesk** [comment]
Try to add the following code to the line 949 in [app/Console/Commands/FetchEmails.php](https://github.com/freescout-helpdesk/freescout/commit/2cea3a6585d5a1da2a570fb25a190fe0d6b25726#diff-e12b566d766fcc92a657c5895fa11b550afb364c47c64512ee5bbe9a5f639666):
```
\Log::error("[Fetch Emails Debug] ".$e->getMessage());
```

After that reproduce the issue and send us messages starting with "[Fetch Emails Debug]" from `laravel-yyyy-mm-dd` in Manage > Logs > App Logs.

**Comment by Maddmax76** [comment]
thank you very much, I did it, but the system does not generate the laravel
file, despite having turned the scheduling and setting the message in
question as "read".
Any ideas?

Il giorno lun 24 lug 2023 alle ore 17:38 FreeScout ***@***.***>
ha scritto:

**Comment by freescout-helpdesk** [comment]
It means the problem is in something else not related to the last releases. It will need to be investigated on your server.

**Comment by freescout-helpdesk** [comment]
You can leave it.

**Comment by Maddmax76** [comment]
Good morning. Forgive me if I bother again on an irrelevant topic, but I would like to know if there is a way to put the mail download activity in debug.
I would like to know exactly when the artisan scheduler connects to the server, what it downloads and the result of the download.
Could you tell me how to do it?

Thank you

**Comment by Maddmax76** [comment]
Maybe I succeeded!
From an outlook I marked as "unread" a mail message sent through an application, one of those messages that are not downloaded by FreeScout.
When the scheduler checked for new messages, the following error came out in the laravel logs:


```
Expected response code 354 but got code "503", with message "503 5.5.1 Bad sequence of commands
" {"exception":"[object] (Swift_TransportException(code: 503): Expected response code 354 but got code \"503\", with message \"503 5.5.1 Bad sequence of commands
\" at /var/www/FreeScout/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:457)
[stacktrace]
#0 /var/www/FreeScout/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(341): Swift_Transport_AbstractSmtpTransport->assertResponseCode()
#1 /var/www/FreeScout/overrides/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand()
#2 /var/www/FreeScout/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(390): Swift_Transport_EsmtpTransport->executeCommand()
#3 /var/www/FreeScout/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(497): Swift_Transport_AbstractSmtpTransport->doDataCommand()
#4 /var/www/FreeScout/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(516): Swift_Transport_AbstractSmtpTransport->doMailTransaction()
#5 /var/www/FreeScout/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(206): Swift_Transport_AbstractSmtpTransport->sendTo()
#6 /var/www/FreeScout/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(71): Swift_Transport_AbstractSmtpTransport->send()
#7 /var/www/FreeScout/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(451): Swift_Mailer->send()
#8 /var/www/FreeScout/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(235): Illuminate\\Mail\\Mailer->sendSwiftMessage()
#9 /var/www/FreeScout/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(125): Illuminate\\Mail\\Mailer->send()
#10 /var/www/FreeScout/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(250): Illuminate\\Mail\\Mailable->send()
#11 /var/www/FreeScout/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(205): Illuminate\\Mail\\Mailer->sendMailable()
#12 /var/www/FreeScout/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php(99): Illuminate\\Mail\\Mailer->send()
#13 /var/www/FreeScout/app/Jobs/SendAutoReply.php(82): Illuminate\\Mail\\PendingMail->send()
#14 [internal function]: App\\Jobs\\SendAutoReply->handle()
#15 /var/www/FreeScout/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#16 /var/www/FreeScout/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#17 /var/www/FreeScout/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#18 /var/www/FreeScout/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#19 /var/www/FreeScout/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call()
#20 /var/www/FreeScout/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#21 /var/www/FreeScout/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/FreeScout/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then()
#23 /var/www/FreeScout/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow()
#24 /var/www/FreeScout/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\\Queue\\CallQueuedHandler->call()
#25 /var/www/FreeScout/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\\Queue\\Jobs\\Job->fire()
#26 /var/www/FreeScout/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\\Queue\\Worker->process()
#27 /var/www/FreeScout/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\\Queue\\Worker->runJob()
#28 /var/www/FreeScout/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon()
#29 /var/www/FreeScout/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#30 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#31 /var/www/FreeScout/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#32 /var/www/FreeScout/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#33 /var/www/FreeScout/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#34 /var/www/FreeScout/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#35 /var/www/FreeScout/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#36 /var/www/FreeScout/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#37 /var/www/FreeScout/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run()
#38 /var/www/FreeScout/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run()
#39 /var/www/FreeScout/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand()
#40 /var/www/FreeScout/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#41 /var/www/FreeScout/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run()
#42 /var/www/FreeScout/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run()
#43 /var/www/FreeScout/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle()
#44 {main}
"}
```

I hope this can shed some light on the mystery of the missing messages!

**Comment by Maddmax76** [comment]
in the mailbox in FreeScout I find a message:

```
from microsoft@unknown

Retrieval using the IMAP4 protocol failed for the following message: 752

The server couldn't retrieve the following message:

The message hasn't been deleted. You might be able to view it using either Outlook or Outlook Web App. You can also contact the sender to find out what the message says.

```

probably this is not the cause of not receiving the mails sent by my application, but only an error due to the fact that I have marked a mail as "unread" using outlook.

**Comment by freescout-helpdesk** [comment]
Some links:

https://answers.microsoft.com/en-us/msoffice/forum/all/the-server-couldnt-retrieve-the-following-message/1f4ef03e-022a-42f0-9a8b-e27582be0880

https://answers.microsoft.com/en-us/outlook_com/forum/all/retrieval-using-the-imap4-protocol-failed-for-the/1dfe2d56-3873-4e5e-b46b-8a89871eddf6

**Comment by Maddmax76** [comment]
OK thank you. I believe the only solution is to pass these emails through the API.

Good day, ciao
