### ISSUE TITLE
Sync Mailbox Permissions with LDAP not working

### ISSUE THREAD

**Issue by eiclu** [freescout-helpdesk/freescout#3478]
When trying to sync mailbox access with LDAP by pressing the "Sync Mailbox Permission Now", Freescout throws the following error:

```
class_exists(): Passing null to parameter #1 ($class) of type string is deprecated {"userId":1,"email":"admin-intern@redacted.net","exception":"[object] (ErrorException(code: 0): class_exists(): Passing null to parameter #1 ($class) of type string is deprecated at /var/www/html/Modules/Ldap/vendor/adldap2/adldap2/src/Query/Processor.php:151)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/html/Modules/Ldap/vendor/adldap2/adldap2/src/Query/Processor.php(151): class_exists()
#2 /var/www/html/Modules/Ldap/vendor/adldap2/adldap2/src/Query/Processor.php(138): Adldap\\Query\\Processor->newModel()
#3 /var/www/html/Modules/Ldap/vendor/adldap2/adldap2/src/Query/Processor.php(66): Adldap\\Query\\Processor->newLdapEntry()
#4 /var/www/html/Modules/Ldap/vendor/adldap2/adldap2/src/Query/Processor.php(94): Adldap\\Query\\Processor->process()
#5 /var/www/html/Modules/Ldap/Overrides/Adldap/Query/Builder.php(450): Adldap\\Query\\Processor->processPaginated()
#6 /var/www/html/Modules/Ldap/Overrides/Adldap/Query/Builder.php(346): Adldap\\Query\\Builder->compatiblePaginationCallback()
#7 /var/www/html/Modules/Ldap/Console/Sync.php(248): Adldap\\Query\\Builder->paginate()
#8 /var/www/html/Modules/Ldap/Console/Sync.php(46): Modules\\Ldap\\Console\\Sync->getUsers()
...
"}
```

By skimming the adldap2/src/Query/Processor.php file it seems that it is missing a null check before calling `class_exists` which probably wasnt required before, but is required by newer PHP versions.

```
/**
 * Creates a new model instance.
 *
 * @param array       $attributes
 * @param string|null $model
 *
 * @return mixed|Entry
 */
public function newModel($attributes = [], $model = null)
{
    $model = (class_exists($model) ? $model : Entry::class);

    return new $model($attributes, $this->builder);
}
```

When adding the check it is working again:

```
public function newModel($attributes = [], $model = null)
{
    $model = ($model !== null && class_exists($model) ? $model : Entry::class);

    return new $model($attributes, $this->builder);
}
```

Also, it seems that [Adldap2](https://github.com/Adldap2/Adldap2) is deprecated in favor of [LdapRecord](https://github.com/DirectoryTree/LdapRecord)

PHP version: 8.2.7
FreeScout version: 1.8.99

**Comment by freescout-helpdesk** [comment]
Fixed in LDAP Module v1.0.30
