### ISSUE TITLE
Error Fetching Emails

### ISSUE THREAD

**Issue by R1CH101** [freescout-helpdesk/freescout#351]
Hi,

On one Mailbox, I get an error when fetching emails:
`Error: iconv(): Wrong charset, conversion from "1252" to "UTF-8//IGNORE" is not allowed; File: /var/www/html/vendor/webklex/laravel-imap/src/IMAP/Query/Query.php (189)`

This is also a fresh installation.
Using Nginx, followed installation guide with the web installer

Any Ideas?
Thanks in advance

**Comment by foliovision** [comment]
Fantastic if this is really fixed. Fetching errors over character set differences has been a nightmare. Thank you!

**Comment by foliovision** [comment]
We had issue with missing email for a full day again.

But running Manage -> System -> Tools -> Fetch Email the error was a bit different:

> Error: Invalid argument supplied for foreach(); File: /home/.../public_html/vendor/webklex/laravel-imap/src/IMAP/Query/Query.php (189)

![freescout-bug](https://user-images.githubusercontent.com/1180948/114345793-a444ba80-9b62-11eb-885e-b91d926da3ae.png)

It's really a problem as it doesn't only stop the single email from being processed, it also stops all the other emails from processing.

I'm also attaching the email which was causing the issue, the name in the email looks like this:

```
Reply-to: "=?UTF-8?B?Kévin?=" <removing-the-actual-user-email@example.com>
From: "=?UTF-8?B?S8Opdmlu?=" <removing-the-actual-user-email@example.com>
```
[The bad email .eml file](https://github.com/freescout-helpdesk/freescout/files/6294206/freescount.cant.import.this.email.eml.txt) (note you may need to change the extension from `.eml.txt to` just `.eml`)

Both this issue and the other similar issue https://github.com/freescout-helpdesk/freescout/issues/360 are tagged "help wanted", so I had a look:

I see that the issue might be with https://github.com/Webklex/laravel-imap but FreeScout seems to be using version 1.2.7 while 2.4.0 is out: https://github.com/Webklex/laravel-imap/blob/master/CHANGELOG.md

So I tried to put in verision 1.2.9 using composer - last of the 1.2.x branch. No improvement.

Next I tried version 1.6.2 - the last release of the 1.x breanch  - but then I only got "Whoops, looks like something went wrong." when trying to run Manage -> System -> Tools -> Fetch Email. The error in Laravel logs is:

> Type error: Argument 1 passed to Webklex\IMAP\Client::openFolder() must be an instance of Webklex\IMAP\Folder, string given, called in /home/dskminak/public_html/vendor/webklex/laravel-imap/src/IMAP/Folder.php on line 137 {"userId":3,"email":"...","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to Webklex\\IMAP\\Client::openFolder() must be an instance of Webklex\\IMAP\\Folder, string given, called in /home/dskminak/public_html/vendor/webklex/laravel-imap/src/IMAP/Folder.php on line 137 at /home/dskminak/public_html/overrides/Webklex/IMAP/Client.php:321)
[stacktrace]
> #0 /home/dskminak/public_html/vendor/webklex/laravel-imap/src/IMAP/Folder.php(137): Webklex\\IMAP\\Client->openFolder('{mail.foliovisi...')
> #1 /home/dskminak/public_html/app/Console/Commands/FetchEmails.php(165): Webklex\\IMAP\\Folder->query()

Version 1.3.1 didn't crash FreeScout anymore, but didn't fix the issue.

1.4.5 gave me that same "Whoops, looks like something went wrong." when trying to run Manage -> System -> Tools -> Fetch Email.

I haven't tried to put in 2.4.0 as I'm sure it would also fail.

So it looks like the webklex/laravel-imap component should be upgraded to the latest version and the FreeScout code fixed to work with it.

Thanks,
Martin

**Comment by freescout-helpdesk** [comment]
Try to comment `throw new GetMessagesFailedException($message);` on line 189 in  /home/.../public_html/vendor/webklex/laravel-imap/src/IMAP/Query/Query.php and post here the error you will get.

**Comment by foliovision** [comment]
It didn't help. I got this error:

> Error: count(): Parameter must be an array or an object that implements Countable; File: /home/dskminak/public_html/app/Console/Commands/FetchEmails.php (203)

And the emails were not imported.

Even if you do not update to latest webklex/laravel-imap for some reason it would make sense to improve the process so that a single email with some encoding issue won't stop the whole processing.

**Comment by freescout-helpdesk** [comment]
It's not supposed to help - we need the full error stack trace. Please send.

**Comment by foliovision** [comment]
Last time I was able to find the full error trace in `storage/logs/laravel-2021-04-12.log`. But I do not see the log file for today - `laravel-2021-04-14.log`. And the error is not in `laravel-2021-04-13.log` either.

So that error doesn't seem to produce the trace somehow.

But actually - when I commented out that line 203 in app/Console/Commands/FetchEmails.php as well: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/FetchEmails.php#L203

It gave me this error trace:

```
[2021-04-14 15:25:03] production.ERROR: Call to a member function sortBy() on null {"userId":3,"email":"...@.....com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a
 member function sortBy() on null at /home/dskminak/public_html/app/Console/Commands/FetchEmails.php:1009)
[stacktrace]
#0 /home/dskminak/public_html/app/Console/Commands/FetchEmails.php(208): App\\Console\\Commands\\FetchEmails->sortMessage(NULL)
#1 /home/dskminak/public_html/app/Console/Commands/FetchEmails.php(90): App\\Console\\Commands\\FetchEmails->fetch(Object(App\\Mailbox))
#2 [internal function]: App\\Console\\Commands\\FetchEmails->handle()
#3 /home/dskminak/public_html/overrides/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#4 /home/dskminak/public_html/overrides/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#5 /home/dskminak/public_html/overrides/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#6 /home/dskminak/public_html/overrides/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#7 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#8 /home/dskminak/public_html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#9 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console
\\OutputStyle))
#10 /home/dskminak/public_html/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#11 /home/dskminak/public_html/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\FetchEmails), Object(Symfony\\Component\\Console\\Input\\ArrayInput
), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#12 /home/dskminak/public_html/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\Buffe
redOutput))
#13 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\
Console\\Output\\BufferedOutput))
#14 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Console/Application.php(177): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console
\\Output\\BufferedOutput))
#15 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(249): Illuminate\\Console\\Application->call('freescout:fetch...', Object(Illuminate\\Support\\Collection), Object(Symfony\\Comp
onent\\Console\\Output\\BufferedOutput))
#16 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\\Foundation\\Console\\Kernel->call('freescout:fetch...', Array, Object(Symfony\\Component\\Console\\Output\\Buffer
edOutput))
#17 /home/dskminak/public_html/app/Http/Controllers/SystemController.php(286): Illuminate\\Support\\Facades\\Facade::__callStatic('call', Array)
#18 [internal function]: App\\Http\\Controllers\\SystemController->toolsExecute(Object(Illuminate\\Http\\Request))
#19 /home/dskminak/public_html/overrides/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#20 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('toolsExecute', Array)
#21 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\SystemControlle
r), 'toolsExecute')
#22 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#23 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route->run()
#24 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 /home/dskminak/public_html/app/Http/Middleware/CheckRole.php(26): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\CheckRole->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /home/dskminak/public_html/app/Http/Middleware/CustomHandle.php(22): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\CustomHandle->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /home/dskminak/public_html/app/Http/Middleware/LogoutIfDeleted.php(28): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\LogoutIfDeleted->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /home/dskminak/public_html/app/Http/Middleware/Localize.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /home/dskminak/public_html/app/Http/Middleware/HttpsRedirect.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\HttpsRedirect->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#41 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#50 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /home/dskminak/public_html/app/Http/Middleware/TokenAuth.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#53 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\TokenAuth->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#56 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#59 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#62 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#65 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#66 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#67 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#68 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#69 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#70 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#71 /home/dskminak/public_html/app/Http/Middleware/TerminateHandler.php(12): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#72 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\TerminateHandler->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#73 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#74 /home/dskminak/public_html/app/Http/Middleware/ResponseHeaders.php(11): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#75 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\ResponseHeaders->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#76 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#77 /home/dskminak/public_html/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#78 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#79 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#80 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#81 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#82 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#83 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#84 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#85 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#86 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#87 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#88 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#89 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#90 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#91 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#92 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#93 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#94 /home/dskminak/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#95 /home/dskminak/public_html/public/index.php(64): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#96 {main}
```

So getting rid of that `throw new GetMessagesFailedException($message);` on line 189 in /home/.../public_html/vendor/webklex/laravel-imap/src/IMAP/Query/Query.php will just mean no messages are returned at all.

**Comment by freescout-helpdesk** [comment]
Still the real reason of the issue is not clear. It looks like you will need to find someone who can debug and fix it. Or you can send us SSH access to support@freescout.net

**Comment by foliovision** [comment]
Could we just provide access to a mailbox with the problematic email in it? That way you could set your test FreeScout instance try download the email and see if you run into the same issue.

**Comment by freescout-helpdesk** [comment]
Yes. If you can provide access to the email address containing the problematic email.

**Comment by foliovision** [comment]
Thank you, I sent the mailbox access information to support@freescout.net

I also ensured that I run into that same issue with this new mailbox:

> Error: Invalid argument supplied for foreach(); File: /home/.../public_html/vendor/webklex/laravel-imap/src/IMAP/Query/Query.php (189)

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.

**Comment by foliovision** [comment]
I updated to 1.7.4 and then added the changes from https://github.com/freescout-helpdesk/freescout/commit/e52711d592d80574d0ef3105907f72b6e24b35eb

It works, thank you very much!
