### ISSUE TITLE
Customer Keeps Receiving Email Notifications After Reply

### ISSUE THREAD

**Issue by bogdan-d** [freescout-helpdesk/freescout#3619]
Hello,

I've encountered an issue where a customer keeps receiving email notifications after a reply is posted on the conversation thread. This has been reported by a customer that he received about 150 email notifications for the same reply, in a 30-minute span from 11:10 to 11:40. I've checked the PHP logs and found an error related to this issue. At 11:40 the docker container was restarted/rebuilt and the issue was resolved. I've attached the error log below.

```
[2023-12-18 11:10:15] production.ERROR: Packets out of order. Expected 1 received 0. Packet size=145 (SQL: insert into `send_logs` (`thread_id`, `message_id`, `email`, `mail_type`, `status`, `customer_id`, `user_id`, `status_message`, `updated_at`, `created_at`) values (3058, reply-3058-899d71fe0c4b89bb@REDACTED, user-email-redacted@gmail.com, 1, 1, 787, , , 2023-12-18 11:10:15, 2023-12-18 11:10:15)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 0): Packets out of order. Expected 1 received 0. Packet size=145 (SQL: insert into `send_logs` (`thread_id`, `message_id`, `email`, `mail_type`, `status`, `customer_id`, `user_id`, `status_message`, `updated_at`, `created_at`) values (3058, reply-3058-899d71fe0c4b89bb@REDACTED, user-email-redacted@gmail.com, 1, 1, 787, , , 2023-12-18 11:10:15, 2023-12-18 11:10:15)) at /www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, ErrorException(code: 0): Packets out of order. Expected 1 received 0. Packet size=145 at /www/html/overrides/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:82)
[stacktrace]
#0 /www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('insert into `se...', Array, Object(Closure))
#1 /www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(447): Illuminate\\Database\\Connection->run('insert into `se...', Array, Object(Closure))
#2 /www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\\Database\\Connection->statement('insert into `se...', Array)
#3 /www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\\Database\\Connection->insert('insert into `se...', Array)
#4 /www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2159): Illuminate\\Database\\Query\\Processors\\Processor->processInsertGetId(Object(Illuminate\\Database\\Query\\Builder), 'insert into `se...', Array, 'id')
#5 /www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1285): Illuminate\\Database\\Query\\Builder->insertGetId(Array, 'id')
#6 /www/html/overrides/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(723): Illuminate\\Database\\Eloquent\\Builder->__call('insertGetId', Array)
#7 /www/html/overrides/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(688): Illuminate\\Database\\Eloquent\\Model->insertAndSetId(Object(Illuminate\\Database\\Eloquent\\Builder), Array)
#8 /www/html/overrides/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(551): Illuminate\\Database\\Eloquent\\Model->performInsert(Object(Illuminate\\Database\\Eloquent\\Builder))
#9 /www/html/app/SendLog.php(111): Illuminate\\Database\\Eloquent\\Model->save()
#10 /www/html/app/Jobs/SendReplyToCustomer.php(547): App\\SendLog::log(3058, 'reply-3058-899d...', 'user-email-redacted@gmail....', 1, 1, 787, NULL, '', NULL)
#11 /www/html/app/Jobs/SendReplyToCustomer.php(475): App\\Jobs\\SendReplyToCustomer->saveToSendLog('', NULL)
#12 [internal function]: App\\Jobs\\SendReplyToCustomer->handle()
#13 /www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(28): call_user_func_array(Array, Array)
#14 /www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 /www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(27): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#16 /www/html/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#17 /www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#18 /www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\SendReplyToCustomer))
#19 /www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\SendReplyToCustomer))
#20 /www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#21 /www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(48): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\SendReplyToCustomer), false)
#22 /www/html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Array)
#23 /www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\\Queue\\Jobs\\Job->fire()
#24 /www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\\Queue\\Worker->process('database', Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Object(Illuminate\\Queue\\WorkerOptions))
#25 /www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), 'database', Object(Illuminate\\Queue\\WorkerOptions))
#26 /www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\\Queue\\Worker->daemon('database', 'emails,default,...', Object(Illuminate\\Queue\\WorkerOptions))
#27 /www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(84): Illuminate\\Queue\\Console\\WorkCommand->runWorker('database', 'emails,default,...')
#28 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#29 /www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(28): call_user_func_array(Array, Array)
#30 /www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#31 /www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(27): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#32 /www/html/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#33 /www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#34 /www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#35 /www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#36 /www/html/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#37 /www/html/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#38 /www/html/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#39 /www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#40 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#41 /www/html/artisan(60): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#42 {main}
"}
```

Please note that ever since the docker container was restarted, the issue has not reoccurred.

Any help on this would be greatly appreciated. Thank you.

PHP version: 8.2.13
FreeScout version: 1.8.112
Database: Mysql (8.0.35-0ubuntu0.22.04.1)
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
The workaround has been added in FreeScout v1.8.114. You'll just need to wait for the new Docker image to be released.
