### ISSUE TITLE
Bug: Error on switching default language in settings

### ISSUE THREAD

**Issue by chriscorns** [freescout-helpdesk/freescout#3620]
I got an error if I change the default language under `/app-settings/general`. The page displays after that only the text "Whoops... see error logfiles". You can find the error stack trace below. The problem is **line 18** in a dynamicly generated file `/var/www/freescout/htdocs/storage/framework/views/bf581556abc07170e1a081bbcaf6f47c04b7e5bb.php`:

```php
<option value="<?php echo e($locale); ?>" <?php if($selected == $locale): ?>selected="selected"<?php endif; ?>><?php echo e($data['name']); ?></option>
``` 

If I add an @-sign before the last PHP command as workaround for me I can access the page:

```php
<option value="<?php echo e($locale); ?>" <?php if($selected == $locale): ?>selected="selected"<?php endif; ?>><?php echo @e($data['name']); ?></option>
``` 

PHP version: 8.2.13
FreeScout version: 1.8.114
Database: Mysql (10.3.39-MariaDB-0+deb10u1-log)
Are you using CloudFlare: No
```
[2023-12-20 11:43:37] production.ERROR: Trying to access array offset on value of type null (View: /var/www/freescout/htdocs/resources/views/partials/locale_options.blade.php) (View: /var/www/freescout/htdocs/resources/views/partials/locale_options.blade.php) (View: /var/www/freescout/htdocs/resources/views/partials/locale_options.blade.php) {"userId":1,"email":"freescout@*******.**","exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null (View: /var/www/freescout/htdocs/resources/views/partials/locale_options.blade.php) (View: /var/www/freescout/htdocs/resources/views/partials/locale_options.blade.php) (View: /var/www/freescout/htdocs/resources/views/partials/locale_options.blade.php) at /var/www/freescout/htdocs/storage/framework/views/bf581556abc07170e1a081bbcaf6f47c04b7e5bb.php:18, ErrorException(code: 0): Trying to access array offset on value of type null (View: /var/www/freescout/htdocs/resources/views/partials/locale_options.blade.php) (View: /var/www/freescout/htdocs/resources/views/partials/locale_options.blade.php) at /var/www/freescout/htdocs/storage/framework/views/bf581556abc07170e1a081bbcaf6f47c04b7e5bb.php:18, ErrorException(code: 0): Trying to access array offset on value of type null (View: /var/www/freescout/htdocs/resources/views/partials/locale_options.blade.php) at /var/www/freescout/htdocs/storage/framework/views/bf581556abc07170e1a081bbcaf6f47c04b7e5bb.php:18, ErrorException(code: 0): Trying to access array offset on value of type null at /var/www/freescout/htdocs/storage/framework/views/bf581556abc07170e1a081bbcaf6f47c04b7e5bb.php:18)
[stacktrace]
#0 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(45): Illuminate\\View\\Engines\\CompilerEngine->handleViewException()
#1 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#2 /var/www/freescout/htdocs/overrides/laravel/framework/src/Illuminate/View/View.php(137): Illuminate\\View\\Engines\\CompilerEngine->get()
#3 /var/www/freescout/htdocs/overrides/laravel/framework/src/Illuminate/View/View.php(120): Illuminate\\View\\View->getContents()
#4 /var/www/freescout/htdocs/overrides/laravel/framework/src/Illuminate/View/View.php(85): Illuminate\\View\\View->renderContents()
#5 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Illuminate\\View\\View->render()
#6 /var/www/freescout/htdocs/overrides/symfony/http-foundation/Response.php(206): Illuminate\\Http\\Response->setContent()
#7 /var/www/freescout/htdocs/overrides/laravel/framework/src/Illuminate/Routing/Router.php(724): Symfony\\Component\\HttpFoundation\\Response->__construct()
#8 /var/www/freescout/htdocs/overrides/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router::toResponse()
#9 /var/www/freescout/htdocs/overrides/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->prepareResponse()
#10 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#11 /var/www/freescout/htdocs/app/Http/Middleware/CheckRole.php(26): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#12 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\CheckRole->handle()
#13 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/freescout/htdocs/app/Http/Middleware/CustomHandle.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#15 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\CustomHandle->handle()
#16 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /var/www/freescout/htdocs/app/Http/Middleware/FrameGuard.php(14): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#18 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\FrameGuard->handle()
#19 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/freescout/htdocs/app/Http/Middleware/LogoutIfDeleted.php(28): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#21 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\LogoutIfDeleted->handle()
#22 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/freescout/htdocs/app/Http/Middleware/Localize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#24 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\Localize->handle()
#25 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/freescout/htdocs/app/Http/Middleware/HttpsRedirect.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#27 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\HttpsRedirect->handle()
#28 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#30 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#31 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/freescout/htdocs/overrides/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#33 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#34 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/freescout/htdocs/overrides/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#36 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#37 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#39 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#40 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/freescout/htdocs/app/Http/Middleware/TokenAuth.php(32): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#42 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\TokenAuth->handle()
#43 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#45 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle()
#46 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#48 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#49 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/freescout/htdocs/overrides/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(61): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#51 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#52 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#54 /var/www/freescout/htdocs/overrides/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Pipeline\\Pipeline->then()
#55 /var/www/freescout/htdocs/overrides/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack()
#56 /var/www/freescout/htdocs/overrides/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute()
#57 /var/www/freescout/htdocs/overrides/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute()
#58 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch()
#59 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#60 /var/www/freescout/htdocs/app/Http/Middleware/TerminateHandler.php(12): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#61 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\TerminateHandler->handle()
#62 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /var/www/freescout/htdocs/app/Http/Middleware/ResponseHeaders.php(11): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#64 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\ResponseHeaders->handle()
#65 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /var/www/freescout/htdocs/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#67 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle()
#68 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#70 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#71 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#72 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#73 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#74 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#75 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#76 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#77 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#78 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#79 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#80 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#81 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#82 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then()
#83 /var/www/freescout/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#84 /var/www/freescout/htdocs/public/index.php(82): Illuminate\\Foundation\\Http\\Kernel->handle()
#85 {main}
"} 

```

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.
