### ISSUE TITLE
Issue with "Show Original" Functionality in FreeScout: Error Retrieving Mail Server Messages

### ISSUE THREAD

**Issue by prajnajogi** [freescout-helpdesk/freescout#3658]
Hello,

I'm Prajna from the Brainstorm Force support team. Our support agents have encountered a problem with Freescout. 

"Show Original" option for user replies results in an error stating, _"The original message could not be loaded from the mail server."_  

Screenshot: https://bsf.d.pr/i/sEQltX 

We are using the latest version of FreeScout and did not find information in the FAQ about resolving this error. 

Additional Information:

PHP version: 7.4.33
FreeScout version: Version 1.8.115
Database: MySQL (5.5.5-10.11.6-MariaDB-1:10.11.6+maria~ubu2204)
Web server details
CloudFlare usage: No

We kindly seek guidance on resolving this issue. Any assistance would be greatly appreciated.  

Thank you

**Comment by freescout-helpdesk** [comment]
Here is the place to debug: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Misc/Mail.php#L697C9-L697C9

https://github.com/freescout-helpdesk/freescout/wiki/Debugging

**Comment by freescout-helpdesk** [comment]
What is the name of the IMAP folder where the email is stored? Is it a nested folder?

**Comment by ByteOven** [comment]
Howdi, 
Much love for the project  :heart: 
Can we get a fix regarding this update ? 
**Sending emails** is not possible due to unhandled error.


`Send error. Call to undefined method App\Misc\Mail::getHashedRelySeparator() (View: /var/www/html/resources/views/emails/customer/reply_fancy.blade.php). Message-ID: reply-2507`



Stack: 
```
error	production	2024-01-06 12:48:36	 Call to undefined method App\Misc\Mail::getHashedRelySeparator() (View: /var/www/html/resources/views/emails/customer/reply_fancy.blade.php) {"exception":"[object] (ErrorException(code: 0): Call to undefined method App\\Misc\\Mail::getHashedRelySeparator() (View: /var/www/html/resources/views/emails/customer/reply_fancy.blade.php) at /var/www/html/storage/framework/views/712e5e7bf636c367963969a03fd3d9bf676d0c52.php:12, Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method App\\Misc\\Mail::getHashedRelySeparator() at /var/www/html/storage/framework/views/712e5e7bf636c367963969a03fd3d9bf676d0c52.php:12)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(47): Illuminate\\View\\Engines\\CompilerEngine->handleViewException()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#2 /var/www/html/overrides/laravel/framework/src/Illuminate/View/View.php(137): Illuminate\\View\\Engines\\CompilerEngine->get()
#3 /var/www/html/overrides/laravel/framework/src/Illuminate/View/View.php(120): Illuminate\\View\\View->getContents()
#4 /var/www/html/overrides/laravel/framework/src/Illuminate/View/View.php(85): Illuminate\\View\\View->renderContents()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(328): Illuminate\\View\\View->render()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(301): Illuminate\\Mail\\Mailer->renderView()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(218): Illuminate\\Mail\\Mailer->addContent()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(125): Illuminate\\Mail\\Mailer->send()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(250): Illuminate\\Mail\\Mailable->send()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(205): Illuminate\\Mail\\Mailer->sendMailable()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php(99): Illuminate\\Mail\\Mailer->send()
#12 /var/www/html/app/Jobs/SendReplyToCustomer.php(275): Illuminate\\Mail\\PendingMail->send()
#13 [internal function]: App\\Jobs\\SendReplyToCustomer->handle()
#14 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#15 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#17 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\\Queue\\CallQueuedHandler->call()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\\Queue\\Jobs\\Job->fire()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\\Queue\\Worker->process()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\\Queue\\Worker->runJob()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#29 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#30 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#31 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#32 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#33 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#35 /var/www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run()
#37 /var/www/html/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run()
#38 /var/www/html/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand()
#39 /var/www/html/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run()
#42 /var/www/html/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle()
#43 {main}
"}
```


Grateful :smiling_face_with_tear:

**Comment by prajnajogi** [comment]
@freescout-helpdesk 

No, it's not a nested folder, and the folder name is "BSF"

Thanks!

**Comment by freescout-helpdesk** [comment]
Check with the latest FreeScout version.
