### ISSUE TITLE
some emails can't be sent App\Jobs\SendEmailReplyError

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#3669]
Some emails don't leave the queue and I can't figure out why:
 
```
App\Jobs\SendEmailReplyError Object
(
    [from] => kontakt@example.de
    [user] => App\User Object
        (
            [connection:protected] => mysql
            [table:protected] => 
            [primaryKey:protected] => id
            [keyType:protected] => int
            [incrementing] => 1
            [with:protected] => Array
                (
                )

            [withCount:protected] => Array
                (
                )

            [perPage:protected] => 15
            [exists] => 1
            [wasRecentlyCreated] => 
            [attributes:protected] => Array
                (
                    [id] => 3
                    [first_name] => John
                    [last_name] => Doe
                    [email] => John@example.de
                    [password] => $2y$10$MmZ2e2Q66ssYtesdfhoj4hljhkjhkdMzE3PMwrHUkn9hd8KzAoo65y
                    [role] => 1
                    [timezone] => Europe/Berlin
                    [photo_url] => fb8971c1137d2999db8f3596e330570e.jpg
                    [type] => 1
                    [status] => 1
                    [invite_state] => 1
                    [invite_hash] => 
                    [emails] => John.Doe@example.de
                    [job_title] => 
                    [phone] => +49 341 2269122
                    [time_format] => 2
                    [enable_kb_shortcuts] => 0
                    [locked] => 0
                    [remember_token] => s1XRx2lL1LG1YhJynkDvhmJasdasdad33A5Kv145f56B1aJllp68rgQ
                    [locale] => de
                    [created_at] => 2023-01-03 18:50:41
                    [updated_at] => 2024-01-07 23:50:20
                    [permissions] => []
                )

            [original:protected] => Array
                (
                    [id] => 3
                    [first_name] => John
                    [last_name] => Doe
                    [email] => John@example.de
                    [password] => $2y$10$MmZ2e2Q66ssYtesdfhoj4hljhkjhkdMzE3PMwrHUkn9hd8KzAoo65y
                    [role] => 1
                    [timezone] => Europe/Berlin
                    [photo_url] => fb8971c1137d2999db8f3596e330570e.jpg
                    [type] => 1
                    [status] => 1
                    [invite_state] => 1
                    [invite_hash] => 
                    [emails] => John.Doe@example.de
                    [job_title] => 
                    [phone] => +49 341 2269122
                    [time_format] => 2
                    [enable_kb_shortcuts] => 0
                    [locked] => 0
                    [remember_token] => s1XRx2lL1LG1YhJynkDvhmJasdasdad33A5Kv145f56B1aJllp68rgQ
                    [locale] => de
                    [created_at] => 2023-01-03 18:50:41
                    [updated_at] => 2024-01-07 23:50:20
                    [permissions] => []
                )

            [changes:protected] => Array
                (
                )

            [casts:protected] => Array
                (
                    [permissions] => array
                )

            [dates:protected] => Array
                (
                )

            [dateFormat:protected] => 
            [appends:protected] => Array
                (
                )

            [dispatchesEvents:protected] => Array
                (
                )

            [observables:protected] => Array
                (
                )

            [relations:protected] => Array
                (
                )

            [touches:protected] => Array
                (
                )

            [timestamps] => 1
            [hidden:protected] => Array
                (
                    [0] => password
                    [1] => remember_token
                )

            [visible:protected] => Array
                (
                )

            [fillable:protected] => Array
                (
                    [0] => role
                    [1] => status
                    [2] => first_name
                    [3] => last_name
                    [4] => email
                    [5] => password
                    [6] => timezone
                    [7] => photo_url
                    [8] => type
                    [9] => emails
                    [10] => job_title
                    [11] => phone
                    [12] => time_format
                    [13] => enable_kb_shortcuts
                    [14] => locale
                )

            [guarded:protected] => Array
                (
                    [0] => role
                )

            [rememberTokenName:protected] => remember_token
            [rememberCacheDriver] => array
        )

    [mailbox] => App\Mailbox Object
        (
            [connection:protected] => mysql
            [table:protected] => 
            [primaryKey:protected] => id
            [keyType:protected] => int
            [incrementing] => 1
            [with:protected] => Array
                (
                )

            [withCount:protected] => Array
                (
                )

            [perPage:protected] => 15
            [exists] => 1
            [wasRecentlyCreated] => 
            [attributes:protected] => Array
                (
                    [id] => 9
                    [name] => John Doe
                    [email] => John.Doe@example.de
                    [aliases] => John@example.de,tp@example.de,
                    [from_name] => 1
                    [from_name_custom] => 
                    [ticket_status] => 2
                    [ticket_assignee] => 2
                    [template] => 1
                    [signature] => 
--

{%mailbox.name%}
                    [out_method] => 3
                    [out_server] => abc.netcup.net
                    [out_username] => John.Doe@example.de
                    [out_password] => eyJpdiI6IjRkWWRuZGxSdFhZNHp2T2xzVlpBU2c9PSIsInZhbHVlIjoiZGlERVJHQkZldXBrWlVOdUF1d2dGVURsRDdYT0JRM0ZJRFh1OUVpZWJ4bz0iLCJtYWMiOiJhOTFjMmFhOWVmM2M5MWE2ZmEwZTkwNGVkZDlmZmExNWU5ODU3NDI3MGY5MDZmNTRhZTQ0M2QyNTA3YTU1ODMyIn0=
                    [out_port] => 46
                    [out_encryption] => 2
                    [in_server] => abc.netcup.net
                    [in_port] => 993
                    [in_username] => John.Doe@example.de
                    [in_password] => eyJpdiI6IjcrS1I0OW5vYXBONHJOdFNUdm50RGc9PSIsInZhbHVlIjoidjhibllCNHliZEFlZWQ4RUwrS2ttVytSeE4rZGl4SkdVM2VzWVFCbWdOUT0iLCJtYWMiOiJjNDkyNjVmMjllMmE5YTEwNTYwZjVjN2FlM2ExYmI0MWViZDNkZmFjMDA0NjgwMjViN2E5ZjNmNWJkZjg5ODVjIn0=
                    [in_protocol] => 1
                    [in_encryption] => 2
                    [auto_reply_enabled] => 0
                    [auto_reply_subject] => 
                    [auto_reply_message] => 
                    [office_hours_enabled] => 0
                    [ratings] => 0
                    [ratings_placement] => 1
                    [ratings_text] => 
                    [created_at] => 2024-01-07 22:37:51
                    [updated_at] => 2024-01-08 17:48:56
                    [in_validate_cert] => 1
                    [in_imap_folders] => ["INBOX"]
                    [auto_bcc] => 
                    [before_reply] => -- Bitte über dieser Linie antworten --
                    [imap_sent_folder] => Sent
                    [meta] => {"mi":{"icon":"b7620050.png","custom":true},"imapmove":{"action":1,"folder":""}}
                    [aliases_reply] => 0
                )

            [original:protected] => Array
                (
                    [id] => 9
                    [name] => John Doe
                    [email] => John.Doe@example.de
                    [aliases] => John@example.de,tp@example.de,
                    [from_name] => 1
                    [from_name_custom] => 
                    [ticket_status] => 2
                    [ticket_assignee] => 2
                    [template] => 1
                    [signature] => 
--

{%mailbox.name%}
                    [out_method] => 3
                    [out_server] => abc.netcup.net
                    [out_username] => John.Doe@example.de
                    [out_password] => eyJpdiI6IjRkWWRuZGxSdFhZNHp2T2xzVlpBU2c9PSIsInZhbHVlIjoiZGlERVJHQkZldXBrWlVOdUF1d2dGVURsRDdYT0JRM0ZJRFh1OUVpZWJ4bz0iLCJtYWMiOiJhOTFjMmFhOWVmM2M5MWE2ZmEwZTkwNGVkZDlmZmExNWU5ODU3NDI3MGY5MDZmNTRhZTQ0M2QyNTA3YTU1ODMyIn0=
                    [out_port] => 46
                    [out_encryption] => 2
                    [in_server] => abc.netcup.net
                    [in_port] => 993
                    [in_username] => John.Doe@example.de
                    [in_password] => eyJpdiI6IjcrS1I0OW5vYXBONHJOdFNUdm50RGc9PSIsInZhbHVlIjoidjhibllCNHliZEFlZWQ4RUwrS2ttVytSeE4rZGl4SkdVM2VzWVFCbWdOUT0iLCJtYWMiOiJjNDkyNjVmMjllMmE5YTEwNTYwZjVjN2FlM2ExYmI0MWViZDNkZmFjMDA0NjgwMjViN2E5ZjNmNWJkZjg5ODVjIn0=
                    [in_protocol] => 1
                    [in_encryption] => 2
                    [auto_reply_enabled] => 0
                    [auto_reply_subject] => 
                    [auto_reply_message] => 
                    [office_hours_enabled] => 0
                    [ratings] => 0
                    [ratings_placement] => 1
                    [ratings_text] => 
                    [created_at] => 2024-01-07 22:37:51
                    [updated_at] => 2024-01-08 17:48:56
                    [in_validate_cert] => 1
                    [in_imap_folders] => ["INBOX"]
                    [auto_bcc] => 
                    [before_reply] => -- Bitte über dieser Linie antworten --
                    [imap_sent_folder] => Sent
                    [meta] => {"mi":{"icon":"b7620050.png","custom":true},"imapmove":{"action":1,"folder":""}}
                    [aliases_reply] => 0
                )

            [changes:protected] => Array
                (
                )

            [casts:protected] => Array
                (
                    [meta] => array
                )

            [dates:protected] => Array
                (
                )

            [dateFormat:protected] => 
            [appends:protected] => Array
                (
                )

            [dispatchesEvents:protected] => Array
                (
                )

            [observables:protected] => Array
                (
                )

            [relations:protected] => Array
                (
                )

            [touches:protected] => Array
                (
                )

            [timestamps] => 1
            [hidden:protected] => Array
                (
                )

            [visible:protected] => Array
                (
                )

            [fillable:protected] => Array
                (
                    [0] => name
                    [1] => email
                    [2] => aliases
                    [3] => aliases_reply
                    [4] => auto_bcc
                    [5] => from_name
                    [6] => from_name_custom
                    [7] => ticket_status
                    [8] => ticket_assignee
                    [9] => template
                    [10] => before_reply
                    [11] => signature
                    [12] => out_method
                    [13] => out_server
                    [14] => out_username
                    [15] => out_password
                    [16] => out_port
                    [17] => out_encryption
                    [18] => in_server
                    [19] => in_port
                    [20] => in_username
                    [21] => in_password
                    [22] => in_protocol
                    [23] => in_encryption
                    [24] => in_validate_cert
                    [25] => auto_reply_enabled
                    [26] => auto_reply_subject
                    [27] => auto_reply_message
                    [28] => office_hours_enabled
                    [29] => ratings
                    [30] => ratings_placement
                    [31] => ratings_text
                    [32] => imap_sent_folder
                )

            [guarded:protected] => Array
                (
                    [0] => *
                )

            [rememberCacheDriver] => array
        )

    [timeout] => 120
    [job:protected] => 
    [connection] => 
    [queue] => emails
    [chainConnection] => 
    [chainQueue] => 
    [delay] => 
    [chained] => Array
        (
        )

)
```

```
Swift_TransportException: Connection could not be established with host mx2ff0.netcup.net [Connection timed out #110] in /path/to/freescout/overrides/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:271
Stack trace:
#0 /path/to/freescout/overrides/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(58): Swift_Transport_StreamBuffer->establishSocketConnection()
#1 /path/to/freescout/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(143): Swift_Transport_StreamBuffer->initialize(Array)
#2 /path/to/freescout/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start()
#3 /path/to/freescout/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(451): Swift_Mailer->send(Object(Swift_Message), Array)
#4 /path/to/freescout/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(235): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#5 /path/to/freescout/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(119): Illuminate\Mail\Mailer->send('emails/user/ema...', Array, Object(Closure))
#6 /path/to/freescout/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(250): Illuminate\Mail\Mailable->send(Object(Illuminate\Mail\Mailer))
#7 /path/to/freescout/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(205): Illuminate\Mail\Mailer->sendMailable(Object(App\Mail\UserEmailReplyError))
#8 /path/to/freescout/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php(99): Illuminate\Mail\Mailer->send(Object(App\Mail\UserEmailReplyError))
#9 /path/to/freescout/app/Jobs/SendEmailReplyError.php(61): Illuminate\Mail\PendingMail->send(Object(App\Mail\UserEmailReplyError))
#10 [internal function]: App\Jobs\SendEmailReplyError->handle()
#11 /path/to/freescout/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(28): call_user_func_array(Array, Array)
#12 /path/to/freescout/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#13 /path/to/freescout/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(27): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#14 /path/to/freescout/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#15 /path/to/freescout/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#16 /path/to/freescout/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\SendEmailReplyError))
#17 /path/to/freescout/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\SendEmailReplyError))
#18 /path/to/freescout/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 /path/to/freescout/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(48): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\SendEmailReplyError), false)
#20 /path/to/freescout/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#21 /path/to/freescout/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\Queue\Jobs\Job->fire()
#22 /path/to/freescout/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions))
#23 /path/to/freescout/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\DatabaseJob), 'database', Object(Illuminate\Queue\WorkerOptions))
#24 /path/to/freescout/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\Queue\Worker->daemon('database', 'emails,default,...', Object(Illuminate\Queue\WorkerOptions))
#25 /path/to/freescout/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(84): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'emails,default,...')
#26 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#27 /path/to/freescout/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(28): call_user_func_array(Array, Array)
#28 /path/to/freescout/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#29 /path/to/freescout/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(27): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#30 /path/to/freescout/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#31 /path/to/freescout/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#32 /path/to/freescout/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#33 /path/to/freescout/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#34 /path/to/freescout/vendor/symfony/console/Application.php(992): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /path/to/freescout/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /path/to/freescout/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /path/to/freescout/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 /path/to/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#39 /path/to/freescout/artisan(60): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#40 {main}
```

PHP version: 8.2.12
FreeScout version: 1.8.117
Database: MySQL
Are you using CloudFlare: No

**Comment by mokkin** [comment]
I think this error has gone. There was a misconfiguration in one SMTP setting.
Sorry for bothering...
