### ISSUE TITLE
Error and issue to reach the system/status page. Install broken

### ISSUE THREAD

**Issue by PeopleInside** [freescout-helpdesk/freescout#3771]
PHP version: 8.3
FreeScout version: 1.8.120
Database: MySQL
Are you using CloudFlare: Just the name server but not using Cloudflare proxy

---

Hi, after my install has been broken, I restored folder and database and cleared cache by SSH and also by tools.php
I'm still not bale to log in if I'm not already logged in and I'm unable to reach the page system/storage to clean the cache from there that resolved my past problems.

Seems top menu is not working.

I have the following error log in storage:

```
[2024-02-06 18:00:49] production.ERROR: Error: file_exists(): open_basedir restriction in effect. File(/var/www/vhosts/domain.ext/httpdocs/subdomains/helpdesk.domain.ext/support/public/storage/js/vars.js) is not within the allowed path(s): (/var/www/vhosts/domain.ext/:/tmp/); File: /var/www/vhosts/domain.ext/httpdocs/subdomains/helpdesk.domain.ext/support/overrides/devfactory/minify/src/Providers/BaseProvider.php (122)  
[2024-02-06 18:00:54] production.ERROR: Trait "League\Flysystem\ConfigAwareTrait" not found {"userId":1,"email":"marcob@domain.ext","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Trait \"League\\Flysystem\\ConfigAwareTrait\" not found at /var/www/vhosts/domain.ext/httpdocs/subdomains/helpdesk.domain.ext/support/vendor/league/flysystem/src/Filesystem.php:19)
[stacktrace]
#0 {main}
"} 
[2024-02-06 18:01:00] production.ERROR: Error: file_exists(): open_basedir restriction in effect. File(/var/www/vhosts/domain.ext/httpdocs/subdomains/helpdesk.domain.ext/support/public/storage/js/vars.js) is not within the allowed path(s): (/var/www/vhosts/domain.ext/:/tmp/); File: /var/www/vhosts/domain.ext/httpdocs/subdomains/helpdesk.domain.ext/support/overrides/devfactory/minify/src/Providers/BaseProvider.php (122)  
[2024-02-06 18:01:01] production.ERROR: Class "Mews\Purifier\PurifierServiceProvider" not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class \"Mews\\Purifier\\PurifierServiceProvider\" not found at /var/www/vhosts/domain.ext/httpdocs/subdomains/helpdesk.domain.ext/support/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:706)
[stacktrace]
#0 /var/www/vhosts/domain.ext/httpdocs/subdomains/helpdesk.domain.ext/support/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(686): Illuminate\\Foundation\\Application->registerDeferredProvider()
#1 /var/www/vhosts/domain.ext/httpdocs/subdomains/helpdesk.domain.ext/support/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(662): Illuminate\\Foundation\\Application->loadDeferredProvider()
#2 /var/www/vhosts/domain.ext/httpdocs/subdomains/helpdesk.domain.ext/support/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(299): Illuminate\\Foundation\\Application->loadDeferredProviders()
#3 /var/www/vhosts/domain.ext/httpdocs/subdomains/helpdesk.domain.ext/support/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(119): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#4 /var/www/vhosts/domain.ext/httpdocs/subdomains/helpdesk.domain.ext/support/artisan(60): Illuminate\\Foundation\\Console\\Kernel->handle()
#5 {main}
"} 
[2024-02-06 18:01:24] production.ERROR: Error: file_exists(): open_basedir restriction in effect. File(/var/www/vhosts/domain.ext/httpdocs/subdomains/helpdesk.domain.ext/support/public/storage/js/vars.js) is not within the allowed path(s): (/var/www/vhosts/domain.ext/:/tmp/); File: /var/www/vhosts/domain.ext/httpdocs/subdomains/helpdesk.domain.ext/support/overrides/devfactory/minify/src/Providers/BaseProvider.php (122)  
[2024-02-06 18:01:31] production.ERROR: Error: file_exists(): open_basedir restriction in effect. File(/var/www/vhosts/domain.ext/httpdocs/subdomains/helpdesk.domain.ext/support/public/storage/js/vars.js) is not within the allowed path(s): (/var/www/vhosts/domain.ext/:/tmp/); File: /var/www/vhosts/domain.ext/httpdocs/subdomains/helpdesk.domain.ext/support/overrides/devfactory/minify/src/Providers/BaseProvider.php (122)  
```

Any idea on how to fix?
Thanks

**Comment by PeopleInside** [comment]
In Plesk Panel need go on domain, PHP settings and disable open_basedir by setting up to none.
This resolved the issue.
