### ISSUE TITLE
Search by Customer Phone number not working on PostgreSQL

### ISSUE THREAD

**Issue by sarsony1** [freescout-helpdesk/freescout#3831]
I got freescout setup and working. I use both API and dahboard and both work just fine and responsive. But whenever I try to search based on customer phone number, I constantly get this error. Doesnt look starightforward bcz if it is a DB issue, the others shouldnt work. But everything else is working just fine.  Plz help 
```
[2024-02-27 10:26:02] production.ERROR: could not find driver (SQL: select * from "options" where ("name" = fetch_emails_last_run) limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 0): could not find driver (SQL: select * from \"options\" where (\"name\" = fetch_emails_last_run) limit 1) at /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/vhosts/current/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /var/www/vhosts/current/overrides/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)
[stacktrace]
#0 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback()
#1 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Database/Connection.php(317): Illuminate\\Database\\Connection->run()
#2 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1718): Illuminate\\Database\\Connection->select()
#3 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1704): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(483): Illuminate\\Database\\Query\\Builder->get()
#5 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(467): Illuminate\\Database\\Eloquent\\Builder->getModels()
#6 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(77): Illuminate\\Database\\Eloquent\\Builder->get()
#7 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(379): Illuminate\\Database\\Eloquent\\Builder->first()
#8 /var/www/vhosts/current/overrides/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1475): Illuminate\\Database\\Eloquent\\Builder->firstOrCreate()
#9 /var/www/vhosts/current/overrides/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1487): Illuminate\\Database\\Eloquent\\Model->__call()
#10 /var/www/vhosts/current/app/Option.php(53): Illuminate\\Database\\Eloquent\\Model::__callStatic()
#11 /var/www/vhosts/current/app/Console/Commands/FetchEmails.php(81): App\\Option::set()
#12 [internal function]: App\\Console\\Commands\\FetchEmails->handle()
#13 /var/www/vhosts/current/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(28): call_user_func_array()
#14 /var/www/vhosts/current/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 /var/www/vhosts/current/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(27): Illuminate\\Container\\BoundMethod::callBoundMethod()
#16 /var/www/vhosts/current/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#17 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#18 /var/www/vhosts/current/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#19 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Symfony\\Component\\Console\\Command\\Command->run()
#20 /var/www/vhosts/current/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run()
#21 /var/www/vhosts/current/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand()
#22 /var/www/vhosts/current/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#23 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run()
#24 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run()
#25 /var/www/vhosts/current/artisan(60): Illuminate\\Foundation\\Console\\Kernel->handle()
#26 {main}
"} 
[2024-02-27 10:26:03] production.ERROR: could not find driver {"exception":"[object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /var/www/vhosts/current/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 0): could not find driver at /var/www/vhosts/current/overrides/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)
[stacktrace]
#0 /var/www/vhosts/current/overrides/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(42): Doctrine\\DBAL\\Driver\\PDO\\Exception::new()
#1 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(64): Doctrine\\DBAL\\Driver\\PDOConnection->__construct()
#2 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(42): Illuminate\\Database\\Connectors\\Connector->createPdoConnection()
#3 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Database/Connectors/PostgresConnector.php(32): Illuminate\\Database\\Connectors\\Connector->createConnection()
#4 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(183): Illuminate\\Database\\Connectors\\PostgresConnector->connect()
#5 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#6 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Database/Connection.php(915): call_user_func()
#7 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Database/Connection.php(940): Illuminate\\Database\\Connection->getPdo()
#8 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Database/Connection.php(399): Illuminate\\Database\\Connection->getReadPdo()
#9 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Database/Connection.php(325): Illuminate\\Database\\Connection->getPdoForSelect()
#10 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Database/Connection.php(657): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#11 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback()
#12 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Database/Connection.php(317): Illuminate\\Database\\Connection->run()
#13 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1718): Illuminate\\Database\\Connection->select()
#14 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1704): Illuminate\\Database\\Query\\Builder->runSelect()
#15 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(483): Illuminate\\Database\\Query\\Builder->get()
#16 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(467): Illuminate\\Database\\Eloquent\\Builder->getModels()
#17 /var/www/vhosts/current/Modules/ApiWebhooks/Console/WebhooksProcess.php(37): Illuminate\\Database\\Eloquent\\Builder->get()
#18 [internal function]: Modules\\ApiWebhooks\\Console\\WebhooksProcess->handle()
#19 /var/www/vhosts/current/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(28): call_user_func_array()
#20 /var/www/vhosts/current/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#21 /var/www/vhosts/current/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(27): Illuminate\\Container\\BoundMethod::callBoundMethod()
#22 /var/www/vhosts/current/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#23 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#24 /var/www/vhosts/current/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#25 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Symfony\\Component\\Console\\Command\\Command->run()
#26 /var/www/vhosts/current/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run()
#27 /var/www/vhosts/current/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand()
#28 /var/www/vhosts/current/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#29 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run()
#30 /var/www/vhosts/current/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run()
#31 /var/www/vhosts/current/artisan(60): Illuminate\\Foundation\\Console\\Kernel->handle()
#32 {main}
"} 
```

**Comment by freescout-helpdesk** [comment]
> But whenever I try to search based on customer phone number

How are you doing it? Can you send a screenshot?

**Comment by sarsony1** [comment]
<img width="1512" alt="Screenshot 2024-02-27 at 11 03 52 AM" src="https://github.com/freescout-helpdesk/freescout/assets/30548386/71e29d95-c456-4136-b31d-055d11e597cf">
 When I click on search, it gives me this error. 
 FYI, I've tried both from here and mailbox homepage

**Comment by sarsony1** [comment]
It did work with double quotes around. Let me know if you have any opinion on this

**Comment by freescout-helpdesk** [comment]
Your DB?

**Comment by sarsony1** [comment]
Its postgres

**Comment by freescout-helpdesk** [comment]
We've reproduced this but with the following error on PostgreSQL:
**"Numeric value out of range"**

Fixed in the `master` branch and will be published in the next release.

**Comment by sarsony1** [comment]
Thanks a lot. Any ETA for the release ?
