### ISSUE TITLE
Error on upgrade to latest version (1.8.122): Class "Barryvdh\Debugbar\ServiceProvider" not found 

### ISSUE THREAD

**Issue by termy21** [freescout-helpdesk/freescout#3857]
**PHP version: PHP 8.1.2-1ubuntu2.14 (cli) (built: Aug 18 2023 11:41:11) (NTS)
FreeScout version: Currently at 1.8.89, trying to upgrade to 1.8.122
Database: MySQL
Are you using CloudFlare: Yes
Hosted in a container with elest.io.**

We update versions using the manual method (Method 5 as defined at https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout).

However, after completely those steps we are receiving this error when attempting to run the site and also when running any command php/artisan command (such as migrate & freescout:clear-cache).

Any help is appreciated.  We've bought ourselves time by restoring from a backup taken before the update.
There is a feature in a recent update we'd like though.

```
In Application.php line 635:
                                                       
  Class "Barryvdh\Debugbar\ServiceProvider" not found  
                                                     
[2024-03-07 21:55:09] production.ERROR: Class "Barryvdh\Debugbar\ServiceProvider" not found {"exceptio
n":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class \"Barryvdh\\De
bugbar\\ServiceProvider\" not found at /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Ap
plication.php:635)
[stacktrace]
#0 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(582): Illuminate\\Foun
dation\\Application->resolveProvider('Barryvdh\\\\Debugb...')
#1 /www/html/overrides/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(89): Illumin
ate\\Foundation\\Application->register('Barryvdh\\\\Debugb...')
#2 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(561): Illuminate\\Foun
dation\\ProviderRepository->load(Array)
#3 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): I
lluminate\\Foundation\\Application->registerConfiguredProviders()
#4 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foun
dation\\Bootstrap\\RegisterProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#5 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\\Foun
dation\\Application->bootstrapWith(Array)
#6 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foun
dation\\Http\\Kernel->bootstrap()
#7 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foun
dation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#8 /www/html/public/index.php(82): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Htt
p\\Request))
#9 {main}
"} 
[2024-03-07 21:55:09] production.ERROR: Call to undefined method TorMorten\Eventy\Facades\Events::acti
on() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call 
to undefined method TorMorten\\Eventy\\Facades\\Events::action() at /www/html/vendor/laravel/framework
/src/Illuminate/Support/Facades/Facade.php:221)
[stacktrace]
#0 /www/html/app/Subscription.php(424): Illuminate\\Support\\Facades\\Facade::__callStatic('action', A
rray)
#1 /www/html/app/Http/Middleware/TerminateHandler.php(18): App\\Subscription::processEvents()
#2 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(218): App\\Http\\Middl
eware\\TerminateHandler->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\JsonRes
ponse))
#3 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(189): Illuminate\\Foun
dation\\Http\\Kernel->terminateMiddleware(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\
JsonResponse))
#4 /www/html/public/index.php(88): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\
Http\\Request), Object(Illuminate\\Http\\JsonResponse))
#5 {main}
"} 
[2024-03-07 21:55:14] production.ERROR: Class "Barryvdh\Debugbar\ServiceProvider" not found {"exceptio
:


```

**Comment by freescout-helpdesk** [comment]
It looks like not much help we can provide here. Maybe try to find someone who can figure it out on your server (https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer).

**Comment by PeopleInside** [comment]
@termy21 I suggest to resume your backup and try again the update using the normal procedure from the system page.
Everything should work fine.

Let us know.

**Comment by termy21** [comment]
I'm following up with Elest.io on this as well, as this install with them has update button in the UI disabled.

![image](https://github.com/freescout-helpdesk/freescout/assets/3581126/fe89acb8-a741-41f2-98a4-001d8ded92b8)

At this point I'm guessing that it may be hidden because:
- either they control the updates (and we have auto-updated turned off on purpose as we want to decide when to manually update).
-  Or, it may be because we have the install flagged with them so that we can run with a few modified core files.  Once we manually update, we'll just re-modify those few core files.

**Comment by freescout-helpdesk** [comment]
> as this install with them has update button in the UI disabled.

If you are using Docker, it will not be there.

**Comment by termy21** [comment]
Thank you.  I have successfully completed the update via their UI and all is good.
