### ISSUE TITLE
PHP 8.1: Manage > Modules does not work due to a PHP error

### ISSUE THREAD

**Issue by alecpl** [freescout-helpdesk/freescout#3940]
```
production.ERROR: basename(): Passing null to parameter #1 ($path) of type string is deprecated {"exception":"[object] (ErrorException(code: 0): basename(): Passing null to parameter #1 ($path) of type string is deprecated at /home/alec/repos/freescout/overrides/symfony/http-foundation/Request.php:1898)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /home/alec/repos/freescout/overrides/symfony/http-foundation/Request.php(1898): basename()
#2 /home/alec/repos/freescout/overrides/symfony/http-foundation/Request.php(1003): Symfony\\Component\\HttpFoundation\\Request->prepareBaseUrl()
#3 /home/alec/repos/freescout/overrides/symfony/http-foundation/Request.php(1999): Symfony\\Component\\HttpFoundation\\Request->getBaseUrl()
#4 /home/alec/repos/freescout/overrides/symfony/http-foundation/Request.php(963): Symfony\\Component\\HttpFoundation\\Request->preparePathInfo()
#5 /home/alec/repos/freescout/overrides/laravel/framework/src/Illuminate/Http/Request.php(138): Symfony\\Component\\HttpFoundation\\Request->getPathInfo()
...
```
The patch fixes the issue
```diff
--- a/overrides/symfony/http-foundation/Request.php
+++ b/overrides/symfony/http-foundation/Request.php
@@ -1891,11 +1891,11 @@ class Request
     {
         $filename = basename($this->server->get('SCRIPT_FILENAME'));
 
-        if (basename($this->server->get('SCRIPT_NAME')) === $filename) {
+        if (basename((string)$this->server->get('SCRIPT_NAME')) === $filename) {
             $baseUrl = $this->server->get('SCRIPT_NAME');
-        } elseif (basename($this->server->get('PHP_SELF')) === $filename) {
+        } elseif (basename((string)$this->server->get('PHP_SELF')) === $filename) {
             $baseUrl = $this->server->get('PHP_SELF');
-        } elseif (basename($this->server->get('ORIG_SCRIPT_NAME')) === $filename) {
+        } elseif (basename((string)$this->server->get('ORIG_SCRIPT_NAME')) === $filename) {
             $baseUrl = $this->server->get('ORIG_SCRIPT_NAME'); // 1and1 shared hosting compatibility
         } else {
             // Backtrack up the script_filename to find the portion matching

```

PHP version: 8.1
FreeScout version: today's

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.
