### ISSUE TITLE
Cron Job giving error

### ISSUE THREAD

**Issue by diondkb** [freescout-helpdesk/freescout#593]
Hi,

I am getting the following error when the cron job runs:-

In ArgvInput.php line 265:
                                           
  Invalid argument supplied for foreach()                                             

X-Powered-By: PHP/7.3.14
Content-type: text/html; charset=UTF-8

Any help would be appreciated

Thanks,
Dion

**Comment by Filoz** [comment]
Hi,
I think that it might be useful if you post the cronjob command that you have scheduled

**Comment by diondkb** [comment]
Hi,

Here we are - 

* | * | * | * | * | php /home/drfc30/public_html/freescout/artisan schedule:run  >> /dev/null 2>&1
-- | -- | -- | -- | -- | --

**Comment by diondkb** [comment]
Found this in the logs - 

Invalid argument supplied for foreach() {"exception":"[object] (ErrorException(code: 0): Invalid argument supplied for foreach() at /home/drfc30/public_html/freescout/vendor/symfony/console/Input/ArgvInput.php:265)
[stacktrace]
#0 /home/drfc30/public_html/freescout/vendor/symfony/console/Input/ArgvInput.php(265): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Invalid argumen...', '/home/drfc30/pu...', 265, Array)
#1 /home/drfc30/public_html/freescout/vendor/symfony/console/Application.php(1007): Symfony\\Component\\Console\\Input\\ArgvInput->getFirstArgument()
#2 /home/drfc30/public_html/freescout/vendor/laravel/framework/src/Illuminate/Console/Application.php(79): Symfony\\Component\\Console\\Application->getCommandName(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#3 /home/drfc30/public_html/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 /home/drfc30/public_html/freescout/artisan(42): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 {main}
"}

**Comment by Filoz** [comment]
Check this issue: 
https://github.com/freescout-helpdesk/freescout/issues/145
He says that was caused by an incomplete configuration


And, this might help: https://laracasts.com/discuss/channels/laravel/invalid-argument-supplied-for-foreach-when-scheduling-task

**Comment by diondkb** [comment]
I went back to the setup of the mailbox and in the connection settings and tested the connection and got an error
![image](https://user-images.githubusercontent.com/8279822/80412952-eb448c00-88ce-11ea-8a1c-a04e50571c2c.png)

These are the settings I use on other clients which work?

**Comment by diondkb** [comment]
Applying nate_nolting's solution worked - not getting the foreach() errors. Still cant connect when clicking test connection in email setup. Also get the following fetch error in fetch logs - 
Error: imap_open(): Couldn't open stream {pop.europe.secureserver.net:995/pop3/ssl}. Can't connect to n1plpop04-v01.prod.ams1.secureserver.net,995: Connection refused; File: /home/drfc30/public_html/freescout/overrides/Webklex/IMAP/Client.php (230)

**Comment by Filoz** [comment]
/usr/bin/php-cli (nate_nolting's solution) looks like a solution for goddy hosting.
Maybe @freescout-helpdesk , it could be added to Troubleshooting? Do you want a pr?

@diondkb 
if you try with godaddy imap instead of pop3, same result? 	
imap.secureserver.net	993 (SSL)

**Comment by freescout-helpdesk** [comment]
> /usr/bin/php-cli (nate_nolting's solution) looks like a solution for goddy hosting.
> Maybe @freescout-helpdesk , it could be added to Troubleshooting? Do you want a pr?

Yes. Feel free to submit a PR, we will check it.

**Comment by diondkb** [comment]
Ok. What is a PR?

**Comment by diondkb** [comment]
I contacted GoDaddy and asked if port 995. They confirmed it was. Is there a setting I need to change because the app is run on the same server as the mail server?

**Comment by diondkb** [comment]
This is the error reported in the 'App Logs'

![image](https://user-images.githubusercontent.com/8279822/81232281-e41b2d80-8ff4-11ea-83cd-d2d9f083ae36.png)

**Comment by freescout-helpdesk** [comment]
Closing for no activity.
