### ISSUE TITLE
postgresql still broken

### ISSUE THREAD

**Issue by xogium** [freescout-helpdesk/freescout#654]
Hi,
just setup freescout here. I still hit the issue with postgresql not working at all with the web installer, so I set it up manually instead. It appeared to work just fine, until executing the cron job:

```
2020-07-07 16:15:03.621 EDT [122563] ERROR:  invalid input syntax for type smallint: ""
2020-07-07 16:15:03.621 EDT [122563] STATEMENT:  select * from "mailboxes" where "in_protocol" <> $1 and "in_server" <> $2 and "in_port" <> $3 and "in
_username" <> $4 and "in_password" <> $5
```

* postgresql version 12.3
* php version 7.4.7
* FreeScout version 1.5.8

Any help would be appreciated.
Thanks !

**Comment by caseyjhol** [comment]
I can confirm the web installer isn't working with PostgreSQL.

* postgresql version 12.2
* php version 7.4.7
* FreeScout version 1.5.8

It creates a `.env` file without any properties set.

**Comment by xogium** [comment]
What is fun is this, also:

* host: localhost
* port: 5432
* db name: freescout
* username: freescout
* password: some_pass

Result: connection errors out with, error 2002 no such file or directory.

* host: 127.0.0.1
* port: 5432
* db name: freescout
* username: freescout
* password: some_pass

Result: errors out with error 2002 connection refused.

I can assure you that postgresql most definitely listens on localhost:

```
ss -tulpn|grep 5432:
tcp   LISTEN 0      244               127.0.0.1:5432       0.0.0.0:*    
users:(("postgres",pid=120608,fd=4))
tcp   LISTEN 0      244                   [::1]:5432          [::]:*    
users:(("postgres",pid=120608,fd=3))
```
@caseyjhol can you reproduce the smallint issue, as well ?

**Comment by xogium** [comment]
And woops, sorry for trying to use markdown via email ;) I just noticed it doesn't work. Ah well.

**Comment by xogium** [comment]
I've also posted the laravel backtrace
[here](http://ix.io/2rav). Hope this is useful.

**Comment by caseyjhol** [comment]
> I've also posted the laravel backtrace
> [here](http://ix.io/2rav). Hope this is useful.

Just in case the link ever goes down:

```
[2020-07-08 00:00:04] production.ERROR: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type smallint: "" (SQL: select * from "mailboxes" where "in_protocol" <>  and "in_server" <>  and "in_port" <>  and "in_username" <>  and "in_password" <> ) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type smallint: \"\" (SQL: select * from \"mailboxes\" where \"in_protocol\" <>  and \"in_server\" <>  and \"in_port\" <>  and \"in_username\" <>  and \"in_password\" <> ) at /usr/local/webapps/freescout/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type smallint: \"\" at /usr/local/webapps/freescout/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type smallint: \"\" at /usr/local/webapps/freescout/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)
[stacktrace]
#0 /usr/local/webapps/freescout/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select * from \"...', Array, Object(Closure))
#1 /usr/local/webapps/freescout/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('select * from \"...', Array, Object(Closure))
#2 /usr/local/webapps/freescout/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1719): Illuminate\\Database\\Connection->select('select * from \"...', Array, true)
#3 /usr/local/webapps/freescout/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1704): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /usr/local/webapps/freescout/vendor/watson/rememberable/src/Query/Builder.php(56): Illuminate\\Database\\Query\\Builder->get(Array)
#5 /usr/local/webapps/freescout/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(483): Watson\\Rememberable\\Query\\Builder->get(Array)
#6 /usr/local/webapps/freescout/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(467): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#7 /usr/local/webapps/freescout/app/Console/Commands/FetchEmails.php(75): Illuminate\\Database\\Eloquent\\Builder->get()
#8 [internal function]: App\\Console\\Commands\\FetchEmails->handle()
#9 /usr/local/webapps/freescout/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#10 /usr/local/webapps/freescout/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /usr/local/webapps/freescout/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#12 /usr/local/webapps/freescout/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#13 /usr/local/webapps/freescout/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#14 /usr/local/webapps/freescout/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#15 /usr/local/webapps/freescout/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#16 /usr/local/webapps/freescout/vendor/symfony/console/Application.php(963): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /usr/local/webapps/freescout/vendor/symfony/console/Application.php(254): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\FetchEmails), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /usr/local/webapps/freescout/vendor/symfony/console/Application.php(147): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /usr/local/webapps/freescout/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /usr/local/webapps/freescout/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /usr/local/webapps/freescout/artisan(43): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 {main}
"}
```

**Comment by freescout-helpdesk** [comment]
Did you manage to fix it?

**Comment by xogium** [comment]
Nop. I'm no coder, so I do not know where to even begin in fixing this. :/

**Comment by freescout-helpdesk** [comment]
Installation wizard with PostgreSQL will be fixed in the next release. You will need to reinstall the FreeScout.

**Comment by freescout-helpdesk** [comment]
Correction, you don't have to reinstall FreeScout, just keep using it.
