### ISSUE TITLE
Reports Module doesn't show in top header bar

### ISSUE THREAD

**Issue by tiredofit** [freescout-helpdesk/freescout#684]
I registered quickly on the demo to see how the reports system would work, and promptly bought the module.
After installing (performing any migrations and so on) I'm not able to see the Reports top header bar on 1.5.10. I couldn't find anything in the settings to enable further other than activating the module, am I missing anything?

**Comment by freescout-helpdesk** [comment]
Anything in logs?

Can you send a screenshot?

**Comment by tiredofit** [comment]
Not much on the screenshot front:
![image](https://user-images.githubusercontent.com/23528985/88485807-a9f36500-cf2d-11ea-9a2d-11dce0388c92.png)

I do have a handful of these in the logs however assume they are unrelated:

````bash
 Aborted. {"production.ERROR: Aborted. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): Aborted. at /www/html/vendor/symfony/console/Helper/QuestionHelper.php:175)
[stacktrace]
#0 /www/html/vendor/symfony/console/Helper/QuestionHelper.php(84): Symfony\\Component\\Console\\Helper\\QuestionHelper->doAsk(Object(Illuminate\\Console\\OutputStyle), Object(Symfony\\Component\\Console\\Question\\ConfirmationQuestion))
#1 /www/html/vendor/symfony/console/Helper/QuestionHelper.php(462): Symfony\\Component\\Console\\Helper\\QuestionHelper->Symfony\\Component\\Console\\Helper\\{closure}()
#2 /www/html/vendor/symfony/console/Helper/QuestionHelper.php(87): Symfony\\Component\\Console\\Helper\\QuestionHelper->validateAttempts(Object(Closure), Object(Illuminate\\Console\\OutputStyle), Object(Symfony\\Component\\Console\\Question\\ConfirmationQuestion))
#3 /www/html/vendor/symfony/console/Helper/SymfonyQuestionHelper.php(53): Symfony\\Component\\Console\\Helper\\QuestionHelper->ask(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle), Object(Symfony\\Component\\Console\\Question\\ConfirmationQuestion))
#4 /www/html/vendor/symfony/console/Style/SymfonyStyle.php(294): Symfony\\Component\\Console\\Helper\\SymfonyQuestionHelper->ask(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle), Object(Symfony\\Component\\Console\\Question\\ConfirmationQuestion))
#5 /www/html/vendor/symfony/console/Style/SymfonyStyle.php(222): Symfony\\Component\\Console\\Style\\SymfonyStyle->askQuestion(Object(Symfony\\Component\\Console\\Question\\ConfirmationQuestion))
#6 /www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(314): Symfony\\Component\\Console\\Style\\SymfonyStyle->confirm('Would you like ...', true)
#7 /data/Modules/Ldap/Console/Import.php(64): Illuminate\\Console\\Command->confirm('Would you like ...', true)
#8 [internal function]: Modules\\Ldap\\Console\\Import->handle()
#9 /www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#10 /www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#12 /www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#13 /www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#14 /www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#15 /www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#16 /www/html/vendor/symfony/console/Application.php(963): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /www/html/vendor/symfony/console/Application.php(254): Symfony\\Component\\Console\\Application->doRunCommand(Object(Modules\\Ldap\\Console\\Import), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /www/html/vendor/symfony/console/Application.php(147): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /www/html/artisan(43): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 {main}
"} 
````

**Comment by freescout-helpdesk** [comment]
Have you managed to solve it?

**Comment by tiredofit** [comment]
No it still doesn't show up no matter what I do after deactivating or reactivating :\

**Comment by freescout-helpdesk** [comment]
Can you open `/reports/conversations` ?

Make sure you have this line https://github.com/freescout-helpdesk/freescout/blob/dist/resources/views/layouts/app.blade.php#L116 in `/resources/views/layouts/app.blade.php`

**Comment by tiredofit** [comment]
I could open the URL just fine, however was also missing line 116. This seems to be an error on my part entirely. When I added that line the Reports module appeared. We'll do a better job at tracking changes to this file in the future (we have added Piwik/Matomo web tracking to this file). Sorry for the bother on something so embarrassingly simple.
